// カード面の「表示用テキスト（英語）」。card-text.ja.js と同じ cardId キーで対応。
// name = 英語カード名（jaは cards-data.js の日本語名を使うため ja ファイルには無い。英語はここで持つ）。
// titleRuby は日本語専用なので英語では常に "".
// 用語の統一（glossary）:
//   ロック=lock / ロックエリア=Lock Area / 山札=deck / 捨て場=discard pile / 手札=hand / ドロー=draw /
//   マス=space / 駒=piece / ゲート=Gate / 到達効果=Arrival Effect(●) / 手札効果=Hand Effect(■) /
//   基本効果=Basic Effect(★) / 移動=move / 強制移動=forced move / 表向き=face-up / 裏向き=face-down /
//   オープンする=flip face-up / 公開する=reveal / 宣言する=declare / 接触=contact / 相手=opponent /
//   全員=each player / 追色N=Color Cost N（【追色N】=【Color Cost N】）/ このフェイズを終了する=End this phase.
export const CARD_TEXT_EN = {
  // --- Normal cards ---
  "red-jump-pad": {
    name: "Jump Pad", titleRuby: "", basic: "", subtitle: "",
    arrival: "Do not add this to your hand. Move 2 spaces in one leap.",
    hand: "Place this face-up on any space other than a Gate.",
    flavor: "Only the first to leap knows the new view.",
  },
  "red-counter-lock": {
    name: "Counter Lock", titleRuby: "", basic: "", subtitle: "",
    arrival: "If you have locked the fewest, draw 1 card.",
    hand: "Usable when contact is declared against you. Nullify that contact. You may lock 1 card from your hand.",
    flavor: "Only those ready to be robbed can rob back.",
  },
  "orange-mass-change": {
    name: "Space Swap", titleRuby: "", basic: "", subtitle: "",
    arrival: "Swap your position with an opponent's within 3 spaces. That opponent does not gain this card's Arrival Effect.",
    hand: "【Color Cost 1】Gain the Arrival Effect above.",
    flavor: "Everyone should stand in another's place at least once.",
  },
  "orange-harvest-sow": {
    name: "Reap and Sow", titleRuby: "", basic: "", subtitle: "",
    arrival: "Add 1 card from any one space to your hand. Place 1 card from your hand face-down on that space.",
    hand: "Gain the Arrival Effect above.",
    flavor: "Hope you sow will always be reaped by someone.",
  },
  "yellow-sleight-of-hand": {
    name: "Magician's Trick -Sleight-", titleRuby: "", basic: "", subtitle: "",
    arrival: "Add 1 card at random from one opponent's hand to your hand. Add 1 card from your hand to that opponent's hand.",
    hand: "Gain the Arrival Effect above.",
    flavor: "I didn't steal it — you just didn't notice.",
  },
  "yellow-gamble": {
    name: "The Gamble", titleRuby: "", basic: "", subtitle: "",
    arrival: "Declare 2 or more colors. Draw and reveal that many cards. If a declared color is among them, discard your entire hand.",
    hand: "Discard 1 card from your hand. Gain the Arrival Effect above. End this phase.",
    flavor: "Fortune never smiles on those who won't bet.",
  },
  "green-joint-construction": {
    name: "Joint Construction", titleRuby: "", basic: "", subtitle: "",
    arrival: "Each player places 1 card face-down, from the deck or their hand, onto an empty space.",
    hand: "Gain the Arrival Effect above.",
    flavor: "Peace cannot be built alone.",
  },
  "green-growing-trees": {
    name: "Proliferating Trees", titleRuby: "", basic: "", subtitle: "",
    arrival: "Place 1 card face-down from the deck onto every empty space within 2 spaces.",
    hand: "Place 1 card face-down from the deck onto each of any 3 spaces.",
    flavor: "One forest begins from one seed.",
  },
  "blue-slum-official": {
    name: "Slum-Born Official", titleRuby: "", basic: "", subtitle: "",
    arrival: "Each player discards down to 3 cards in hand.",
    hand: "If you have 1 or fewer cards in hand, draw 2 cards. End this phase.",
    flavor: "Yesterday's pauper makes today's laws.",
  },
  "blue-choosable-trap": {
    name: "Trap of Choice", titleRuby: "", basic: "", subtitle: "",
    arrival: "Gain one of the following effects:\n・Discard half of your hand.\n・You are forced to move to your Gate.\n・Discard 1 of your locked cards.",
    hand: "Place this card face-down on any space.",
    flavor: "It looks like you have a choice. That is the trap.",
  },
  "pink-party": {
    name: "Party", titleRuby: "", basic: "", subtitle: "",
    arrival: "Each player gains one of the following effects:\n・Move 1 space; do not gain the Arrival Effect at the destination.\n・Add any 1 card on the field to your hand.\n・Flip any 2 cards on the field face-up.",
    hand: "Place this face-down on any space.",
    flavor: "When the feast ends, may everyone be smiling.",
  },
  "pink-present": {
    name: "Present", titleRuby: "", basic: "", subtitle: "",
    arrival: "Each player who has locked the fewest draws 1 card.",
    hand: "Place this face-down adjacent to an opponent. Draw 1 card.",
    flavor: "The joy of giving runs deeper than that of receiving.",
  },
  "purple-trial-ritual": {
    name: "Ritual of Trials", titleRuby: "", basic: "", subtitle: "",
    arrival: "Declare 3 colors. Place 1 card face-up from the deck adjacent to you. Move to that space; do not gain the Arrival Effect there. If the placed card is a declared color, repeat this effect.",
    hand: "Gain the Arrival Effect above.",
    flavor: "Only trials know the road to truth.",
  },
  "purple-sorry": {
    name: "So Sorry!", titleRuby: "", basic: "", subtitle: "",
    arrival: "Move 1 space.",
    hand: "【Color Cost 1】Usable when an opponent declares their final lock. Add 1 of that opponent's locked cards to your hand.",
    flavor: "If \"sorry\" were enough, there would be no wars.",
  },
  "rainbow-shard": {
    name: "Prism Shard", titleRuby: "",
    basic: "This is every color, and cannot be locked during the Lock Phase.",
    subtitle: "",
    arrival: "This has no Arrival Effect.",
    hand: "Gain one of the following effects:\n・Draw 1 card.\n・Usable when you have two \"Prism Shard\" (including this) in your hand. Lock those two onto any one location. Draw 2 cards.",
    flavor: "It was not broken. It was merely divided.",
  },
  "white-radiance": {
    name: "Prismatic Radiance", titleRuby: "", basic: "", subtitle: "",
    arrival: "Each player draws 3 cards. Discard this card.",
    hand: "Each player draws 3 cards. End this phase.",
    flavor: "Joy filled the sky, and no one noticed the truth.",
  },
  "white-awakening": {
    name: "Awakening of the White Will", titleRuby: "", basic: "", subtitle: "",
    arrival: "Discard all face-up cards on the field.",
    hand: "Place 1 card face-down from the deck on top of every face-up card on the field.",
    flavor: "I saved the world. Or so I believed.",
  },
  "black-faded-cat": {
    name: "Faded Cat", titleRuby: "", basic: "", subtitle: "",
    arrival: "Discard this. Each player discards their entire hand and draws 1 card.",
    hand: "Discard any number of your locked cards. Draw 3 cards for each card discarded this way. End this phase.",
    flavor: "With every stroke, the world fades a little.",
  },
  "black-contract-brand": {
    name: "Brand of Black Temptation", titleRuby: "",
    basic: "During your Lock Phase, if you do not lock, you may draw 1 card. If you lock onto the Lock Area of this card's color, discard 2 cards from your hand and place this face-down on any space.",
    subtitle: "",
    arrival: "Place this face-up onto an empty Lock Area of yours.",
    hand: "Place this face-down on any space.",
    flavor: "Is that brand the mark of the strong, or of the cursed?",
  },
  // --- Eternal cards (Basic ★ is shared; the ability name 《...》 is inline in the Hand Effect) ---
  "eternal-red": {
    name: "Wainauea, the Crimson Volcano", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《Crimson Rain》: 【Color Cost 1】Discard all cards on any one space.",
    flavor: "Do not fear the end. Flame is also a beginning.",
  },
  "eternal-orange": {
    name: "Malmego, the Forbidden Fruit", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《The Fruit's Offer》: 【Color Cost 1】Draw 4 cards. Reveal them. Their Hand Effects cannot be used this turn. If an orange card is among them, discard your entire hand, and you cannot move this turn.",
    flavor: "Whoever gains everything first loses everything once.",
  },
  "eternal-yellow": {
    name: "Domus Nero, the Golden Palace", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《Tycoon's Dignity》: 【Color Cost 1】Draw 2 cards. Each opponent draws 1 card. This effect can be gained only once per turn.",
    flavor: "Let the wealthy share with the poor. What returns after — gratitude, or fangs?",
  },
  "eternal-green": {
    name: "Manzwood, the Miracle Forest", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《Eternal Vitality》: 【Color Cost 1】Draw 1 card.",
    flavor: "The green is calling. In this forest, surely a miracle can be made.",
  },
  "eternal-blue": {
    name: "Prydwen, the Drifting Ship", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《Mystic Voyage》: 【Color Cost 1】Place 1 card face-down from the deck onto each of any 2 spaces.",
    flavor: "Do not waver — tonight, the blue will open the way.",
  },
  "eternal-pink": {
    name: "Konohanasakuya, the Cherry of Bonds", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《Coming of Love》: 【Color Cost 1】Move an opponent adjacent to you. You cannot make contact this turn.",
    flavor: "Let us meet here again — so we promised, beneath this cherry tree.",
  },
  "eternal-purple": {
    name: "Gentechnik, the Endless Chemistry", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "",
    arrival: "",
    hand: "《Gene Splicing》: 【Color Cost 1】Add 1 card from any one space to your hand. Place 1 card face-down from the deck on that space.",
    flavor: "This world is full of wonder. Chemistry never ends.",
  },
  // --- First cards (Basic ★ shared; separate ability name in subtitle; Hand Effect leads with 【Color Cost 1】(...)) ---
  "first-red": {
    name: "Red Cube: Phoenix", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Color of Rebirth》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.) Add the second card from the top of the discard pile to your hand.",
    flavor: "",
  },
  "first-orange": {
    name: "Orange Cube: Harvest", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Hour of Harvest》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.) Add 1 card within 2 spaces to your hand.",
    flavor: "",
  },
  "first-yellow": {
    name: "Yellow Cube: Saffron", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Flash》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.) You may flip up to 4 cards within 2 spaces face-up.",
    flavor: "",
  },
  "first-green": {
    name: "Green Cube: Verdian", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Earnest Sprout》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.) Draw 2 cards and reveal them all. At the end of the turn, discard them. This effect can be gained only once per turn.",
    flavor: "",
  },
  "first-blue": {
    name: "Blue Cube: Celestia", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Unconscious Absorption》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.) From the hand of each opponent who has 2 or more cards, choose 1 card at random, and discard them.",
    flavor: "",
  },
  "first-pink": {
    name: "Pink Cube: Serenade", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Hour of Longing》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.) Lock 1 card from your hand; however, you cannot make your final lock. This effect can be gained only once per turn.",
    flavor: "",
  },
  "first-purple": {
    name: "Purple Cube: Dimension", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is locked, and doing so does not discard it.",
    subtitle: "《Spatial Control》",
    arrival: "",
    hand: "【Color Cost 1】(Discard 1 card of this card's color from your hand to gain the following effect.)\nYour normal moves this turn move 2 spaces in one leap.",
    flavor: "",
  },
  "first-noir": {
    name: "Black Cube: Noir", titleRuby: "",
    basic: "This cannot be targeted by other cards' effects. Its Hand Effect can be used even while this is placed in a Lock Area, and doing so does not discard it.",
    subtitle: "《Extraction》",
    arrival: "",
    hand: "Lock 1 card onto the Lock Area of this card's color. If you do, draw 1 card and move 1 space.",
    flavor: "",
  },
};
