// アプリのUI文言（メニュー・ボタン等）の多言語化。カードのテキスト(card-text)とは別レイヤー。
// t(key, params) が現在の言語(getLang)の文字列を返す。未定義キーは ja にフォールバックし、
// ja にも無ければキー文字列をそのまま返す（開発中の抜けが画面に見えるように）。
// params は {name} 形式のプレースホルダを置換する（例: t("home.comingSoon", {label:"X"})）。
//
// UI英語化は段階的に進める。まずは最も目に付く画面（ホーム）から。翻訳済みのキーだけを
// ここに足していき、各ファイルはハードコード文字列を t("...") に置き換える。
import { getLang } from "./i18n.js";

const UI = {
  ja: {
    // --- ホーム画面（home-screen.js） ---
    "home.subtitle": "ホーム",
    "home.tile.tutorial": "物語チュートリアル",
    "home.tile.match": "CPUマッチ＆フレンドリーマッチ",
    "home.tile.ranked": "フリーマッチ（ランク戦）",
    "home.tile.shop": "ショップ",
    "home.tile.ranking": "ランキング",
    "home.tile.mypage": "マイページ／マイデッキ編集",
    "home.tile.codex": "図鑑／ルールブック",
    "home.tile.news": "お知らせ／更新情報",
    "home.comingSoon": "「{label}」は近日公開予定です。お楽しみに！",
    "home.comingSoonBadge": "近日公開",
    "home.newBadge": "NEW",
    "home.matchChoice.title": "対戦モードを選択",
    "home.matchChoice.friendly": "フレンドリーマッチ",
    "home.matchChoice.friendlyDesc": "オンラインで対戦（部屋を作る／参加する）",
    "home.matchChoice.cpu": "CPU戦（1人用）",
    "home.matchChoice.cpuDesc": "この端末でCPUと対戦（ログイン不要）",
    "home.matchChoice.difficultyLabel": "🤖 CPUの強さ（CPU戦のみ）",
    "home.matchChoice.difficultyHint": "新人＝ランダム／中級・上級＝賢い思考／最強＝伏せカードののぞき見あり",
    "home.matchChoice.countLabel": "👥 人数（CPU戦のみ）",
    "home.matchChoice.countHint": "あなた＋CPU（3人・4人はCPUが2体・3体に増えます）",
    "home.rankLabel": "あなたのランク",
    "home.rankAboutTitle": "ランク戦について",
    "home.waitingBadge": "🟢 {count}人が対戦募集中！",
    "common.back": "← 戻る",
    // --- CPUの強さ・人数（home / options 共有） ---
    "cpu.diff.rookie": "新人",
    "cpu.diff.intermediate": "中級",
    "cpu.diff.advanced": "上級",
    "cpu.diff.master": "最強",
    "cpu.count.2": "2人",
    "cpu.count.3": "3人",
    "cpu.count.4": "4人",
    // --- オプション（options-menu.js） ---
    "opt.title": "オプション",
    "opt.basicSettings": "基本設定",
    "opt.detailSettings": "詳細設定",
    "opt.detailSettingsHint": "画面の見え方・動作の軽さ・CPU戦・通知・ショートカットなど",
    "opt.backToBasic": "← 基本設定へ戻る",
    "opt.reset": "戻す",
    "opt.soundVolume": "効果音の音量",
    "opt.bgmVolume": "BGMの音量",
    "opt.langNote": "現在はカードのテキストのみ翻訳されます（メニュー等は順次英語化中）。",
    "opt.cardPreviewSize": "カードを拡大表示する大きさ",
    "opt.cardPreviewSide": "カード拡大を出す向き",
    "opt.cpuSpeed": "CPUの速さ",
    "opt.cpuStrength": "CPUの強さ",
    "opt.resetAccount": "アカウント設定を初期化する",
    "opt.resetAccountDesc": "名前・アバター・駒スキン・プレイマット・カード裏面・背景画像を既定に戻します。",
    "opt.resetAccountConfirm": "本当に初期化しますか？（もう一度クリック）",
    "opt.resetAccountBusy": "初期化中…",
    "opt.resetAccountFailed": "初期化に失敗しました",
    "opt.statsLink": "🏆 戦績管理システムのプレイヤーと連携",
    "opt.statsLinkSelect": "選択する",
    "opt.statsLinkDone": "✅ 連携済みです",
    "opt.statsLinkGoogleOnly": "Googleアカウントでログインしていないと連携できません。",
    "opt.statsLinkReloginGoogle": "Googleアカウントでログインしなおす",
    "opt.pressKey": "キーを押してください…",
    // 続き299「基本設定のUIを整備（ライトユーザーに優しくない）」で、セクション名を
    // 「機能の種類」から「困りごと」へ、項目名を「何が起きるか」の言葉へ書き換えた。
    // 旧 volume/display/autoTimer/lockArea/reduceAnim はもう使っていないが、他所からの
    // 参照が残っていても壊れないようキー自体は残す。
    "opt.sec.group.volume": "音量",
    "opt.sec.group.display": "表示・演出",
    "opt.sec.group.autoTimer": "自動処理・タイマー",
    "opt.sec.group.common": "よく使う設定",
    "opt.sec.group.heavy": "動きが重い・カクつくとき",
    "opt.sec.group.look": "画面の見え方",
    "opt.sec.group.auto": "カードの効果を自動で処理する",
    "opt.sec.group.advanced": "テスト用・上級者向け",
    "opt.chk.boardIllustOnly": "盤面のカードを絵だけで表示する（遠くからでも見分けやすい／手札と拡大表示はそのまま）",
    "opt.chk.fixedHand": "自分の手札をいつも画面の下に置く（盤面を拡大しても見切れない）",
    "opt.chk.flatten2d": "盤面を平らな2D表示にする（タブレットで画面がちらつく時に）",
    "opt.chk.fullscreen": "全画面で遊ぶ（ブラウザのタブやURL欄を隠す）",
    "opt.chk.opponentBaseTimer": "相手の持ち時間も表示する",
    "opt.chk.actionConfirm": "ロックやカードを使う前に確認する（うっかり操作を防ぐ）",
    "opt.sec.lockArea": "ロックエリア関連",
    "opt.chk.lockAreaBar": "ロックエリアのバーを表示する",
    "opt.chk.lockColor": "ロックエリアに色を付ける",
    "opt.sec.modalDuration": "お知らせの表示時間",
    "opt.sec.reduceAnim": "アニメーションを減らす（動作が重い時に）",
    "opt.chk.disableFlight": "駒やカードが飛ぶ動きをやめる",
    "opt.chk.disableArrival": "到達・ロックの光る演出をやめる",
    "opt.chk.disableGlow": "ずっと光り続ける演出をやめる（手番の光・砂時計のロープなど）",
    "opt.chk.cpuAutoAdvance": "CPUの結果通知を自動で進める（OFFにするとクリックするまで表示）",
    "opt.rankedAutoFixed": "ランク戦では自動処理は常にONで固定されます。",
    "opt.autoProcessing": "カード効果を自動処理する",
    "opt.emergencyEndTurn": "🚨 緊急ターン終了",
    "opt.sec.cpuBattle": "CPU戦（1人用）",
    "opt.sec.rankedNotify": "ランク戦の通知",
    "opt.sec.shortcuts": "ショートカットキー（プレイヤー用ボタン）",
    "opt.shortcutRecommended": "⭐ おすすめ",
    "opt.adminMode": "⚙ 管理者モード",
    "opt.notify.enable": "対戦相手が現れたら通知する",
    "opt.notify.timeLabel": "通知してもいい時間帯",
    "opt.notify.hint": "開始と終了を同じ時刻にすると終日OKです。開始＞終了なら夜をまたぎます（例 22時〜6時）。",
    // --- ゲーム中のボタン（main.js） ---
    "btn.endTurn.caption": "ターン終了",
    "btn.endTurn.detail1": "自分のターンを終え、次のプレイヤーへ手番を渡します。",
    "btn.endTurn.detail2": "相手のゲートに自分の駒が乗っている場合、ターン終了時に「相手ゲート侵攻ボーナス」が自動的に処理されます。",
    "btn.endTurn.otherTurn": "今は{name}のターン中です",
    "btn.endTurn.otherPriority": "今は{name}が優先権を持っています",
    "btn.endTurn.tooltipSelf": "自分のターンを終了します",
    "btn.endTurn.tooltipLocal": "{name}のターンを終了します",
    "btn.boardZoom.caption": "盤面拡大",
    "btn.boardZoom.label0": "盤面拡大",
    "btn.boardZoom.label1": "もっと拡大",
    "btn.boardZoom.label2": "元に戻す",
    "btn.boardZoom.returnToView": "元の画角に戻る",
    "btn.boardZoom.detail1": "盤面全体をズームして見やすくします。まだ画角を登録していない間は、押すたびに「拡大」→「もっと拡大」→「元に戻す」の3段階を切り替えます。",
    "btn.boardZoom.detail2": "マウスホイールでの自由なズームや中クリックドラッグでの視点移動を一度でも使うと、代わりに「元の画角に戻る」ボタンに変わります。その間だけ現れる点滅した「拡大率登録」ボタンを押すと、今の画角を登録できます。登録後は、通常表示からこのボタンを押すと登録した画角へ一気に切り替わります。",
    "btn.handShuffle.caption": "手札シャッフル",
    "btn.handShuffle.tooltip": "自分の手札の並び順をシャッフルします（カードの中身は変わりません）",
    "btn.handShuffle.detail1": "自分の手札の並び順だけをシャッフルします。カードの中身（持っている手札）自体は変わりません。",
    "btn.handShuffle.detail2": "相手に手の内を推測されにくくするための、見た目上の演出です。",
    "btn.draw.caption": "1枚ドロー",
    "btn.draw.tooltip": "山札から1枚引いて手札に加えます",
    "btn.draw.detail1": "山札の一番上のカードを1枚引いて、自分の手札に加えます。",
    "btn.draw.detail2": "山札が無くなった場合は、捨て場を裏向きのまま新しい山札とします（シャッフルはしません）。",
    "btn.publicDraw.caption": "公開ドロー",
    "btn.publicDraw.tooltip": "山札から1枚、表向きで公開ドローします",
    "btn.publicDraw.detail1": "山札の一番上のカードを1枚引き、表向きのまま手札の近くに公開して並べます（扇状の手札には直接入りません）。",
    "btn.publicDraw.detail2": "「手札シャッフル」または「ターンを終了する」を押すと、公開ドローしたカードがまとめて通常の手札へ合流します。",
    // --- フェイズ案内板（phase-guide.js。tutorial.js/help.jsとも共有） ---
    "phase.titleSuffix": "{label}フェイズ",
    "phase.lock.label": "ロック",
    "phase.lock.short": "手札を1枚だけロックできます（任意）",
    "phase.lock.d1": "あなたの手札を1枚だけロックしてもよい（ロックしなくてもよい）。",
    "phase.lock.d2": "ロックしたカードは原則、手札ではなくなり手札効果を使用できない（例外: ファーストカードとエターナルカードの手札効果は特別に使用できる）。",
    "phase.hand.label": "ハンド",
    "phase.hand.short": "手札を何枚でも使えます（任意）",
    "phase.hand.d1": "あなたの手札を何枚でも使ってもよい（使わなくてもよい）。手札効果はそのカード自身を捨てることで得ることができる。",
    "phase.hand.d2": "使用する時以外、手札は原則、相手に見せないようにプレイする。手札枚数に上限はない。",
    "phase.move.label": "ムーブ",
    "phase.move.short": "「移動」か「接触」のどちらかを必ず行います",
    "phase.move.d1": "ムーブフェイズでは、次のどちらか一方を必ず行います。",
    "phase.move.d2": "🚶 移動：自分の隣（前後左右の4マス）の、カードだけが置かれたマスへ駒を置きます。",
    "phase.move.d3": "　カードが裏向きならオープンします。表向きなら「到達」効果が発動し、そのカードは原則そのまま手札に加わります。",
    "phase.move.d4": "　相手の駒がいるマスへは移動できません。",
    "phase.move.d5": "🤝 接触：隣にいる相手の駒を選び、その相手の手札から無作為に1枚もらいます。",
    "phase.move.d6": "　接触された相手は自分のゲートへ強制移動します（接触した自分自身は動きません）。",
    "phase.move.d7": "📥 隣に「カード」も「相手の駒」も無い場合：隣の任意の1マスへ山札から1枚表向きに置いてターンを終了します。",
    "phase.autoSkip.caption": "自動送り",
    "phase.autoSkip.on": "ON",
    "phase.autoSkip.off": "OFF",
    "phase.autoSkip.titleOn": "フェイズ自動送り: ON（することが無いフェイズは自動でスキップします）",
    "phase.autoSkip.titleOff": "フェイズ自動送り: OFF（自分でスキップを押すまでフェイズを送りません。ロックできる手札が無いこと等を相手に悟られません）",

    // --- オープニング/ログイン画面（opening-screen.js） ---
    "opening.loginToggle": "ログイン",
    "opening.testMode": "テストモード",
    "opening.testMode.tip": "1画面で複数人分を動かせる検証用の盤面へ直接進みます（開発・動作確認用）",
    "opening.adminPanel": "🔧 管理者パネル",
    "opening.adminPanel.tip": "管理者モード（設定・利用状況・ユーザー一覧など）を開きます",
    "opening.versionTip": "アプリのバージョン（デプロイ日時）",
    "opening.clickToClose": "クリックで閉じる",
    "opening.clickToSkip": "クリックでスキップ",
    "opening.localPlay": "ローカルでプレイ（ログイン不要）",
    "opening.onlineLoadFail": "オンライン機能を読み込めませんでした。ローカルでプレイできます。",
    "opening.loggedInTitle": "🌐 ログイン中（{name}）",
    "opening.continueOnline": "オンラインで続ける",
    "opening.logout": "ログアウト",
    "opening.testModeHint": "🧪 テストモード：ログイン完了後、「オンラインで続ける」を経由せず直接検証用の盤面へ進みます。通常のオンライン対戦をしたい場合は右上の✕で引き返してください。",
    "opening.googleLogin": "Googleでログイン",
    "opening.error": "エラー: {msg}",
    "opening.googleInfo.title": "アカウントでログインするメリット",
    "opening.googleInfo.b1": "名前・アバター・駒スキンなどの設定が、別の端末・別のブラウザからログインしても引き継がれます。",
    "opening.googleInfo.b2": "戦績管理システムのプレイヤーとの連携も、アカウントに紐づけて保存されるため、次にログインした時も選び直す必要がありません。",
    "opening.googleInfo.b3": "ゲストログインと違い、ログアウトしたり端末を変えたりしても、同じアカウントとして続けて遊べます。",
    "opening.guestLogin": "ゲストでログイン",
    "opening.loggingIn": "ログイン中...",
    "opening.guestInfo.title": "ゲストログインについて",
    "opening.guestInfo.b1": "メールアドレスの登録・確認は不要で、今すぐそのままオンライン対戦に参加できます。",
    "opening.guestInfo.b2": "ただし一度ログアウトしたり、別の端末・別のブラウザからアクセスすると同じアカウントには戻れません（ゲストアカウントを後から引き継ぐ手段は現在ありません）。",
    "opening.guestInfo.b3": "何度も遊ぶ予定がある場合や、名前・アバター・駒スキン等の設定を長く使い続けたい場合は、上のGoogleでログインすることをおすすめします。",
    "opening.guestConfirm.title": "⚠️ ゲストでログインする前に",
    "opening.guestConfirm.body": "ゲストログインでは、ランキングへの参加や、名前・アバター・駒スキン等の設定の記憶といった恩恵を受けられません。また、一度ログアウトしたり別の端末・別のブラウザからアクセスすると、このアカウントには二度と戻れません。",
    "opening.guestConfirm.yes": "承知の上でゲストで始める",
    "opening.guestConfirm.no": "やめる",
    "opening.moreLogin.closed": "その他のログイン方法（メール） ▾",
    "opening.moreLogin.open": "その他のログイン方法（メール） ▴",
    "opening.emailPlaceholder": "メールアドレス",
    "opening.sendMagicLink": "マジックリンクを送る",
    "opening.sending": "送信中...",
    "opening.checkEmail": "メールを確認し、届いたリンクを開いてください。",
    // ストーリーテロップ（起動時の導入テロップ、空行は本文の""で表現）
    "opening.story.1": "ここは異世界「ファルベンド」",
    "opening.story.2": "世界は「色」で満ちている",
    "opening.story.3": "この世界には、7つの国があり",
    "opening.story.4": "各国はそれぞれの色を治めている",
    "opening.story.5": "そして、均衡は保たれ平和を築いていた",
    "opening.story.6": "しかし、世界の「色」は突如――",
    "opening.story.7": "消えた",
    "opening.story.8": "各国は、それぞれ国宝を有していた",
    "opening.story.9": "それはその国の「色」を纏った「キューブ」",
    "opening.story.10": "しかし、なぜかその「キューブ」だけは",
    "opening.story.11": "「色」を失わなかった",
    "opening.story.12": "色を失った世界で民は輝きを失い途方にくれていた",
    "opening.story.13": "やがて各国の国王は",
    "opening.story.14": "その「キューブ」の「特殊な力」に気付く",
    "opening.story.15": "そうそれは、「色」を「具現化する力」だった",
    "opening.story.16": "「色」はこの世のあらゆるものと",
    "opening.story.17": "密接に関わっている",
    "opening.story.18": "モノ、記憶、能力、あらゆるものに",
    "opening.story.19": "ある時「キューブ」の力が国王に語りかける",
    "opening.story.20": "-7つの色を集めよ-",
    "opening.story.21": "7つの色を集めたら　一体どうなるのか",
    "opening.story.22": "各国のそれぞれの野望、思惑、理想が交錯する中",
    "opening.story.23": "7色を巡る戦いが",
    "opening.story.24": "今、はじまる",

    // --- ショップ（shop.js / shop-content.js） ---
    "shop.title": "ショップ",
    "shop.cat.pieceSkin": "🎲 駒スキン",
    "shop.cat.cardBack": "🂠 カード裏面",
    "shop.cat.playmat": "🟩 プレイマット",
    "shop.cat.background": "🖼️ 背景画像",
    "shop.cat.pet": "🐾 ペット",
    "shop.cat.avatar": "😀 アバター",
    "shop.cat.mydeck": "🃏 マイデッキ枠",
    "shop.ribbon.free": "無料",
    "shop.ribbon.owned": "所持済み",
    "shop.balance.loginPrompt": "ログインすると通貨を貯められます",
    "shop.balance": "所持通貨: 🪙 {n}",
    "shop.completion": "🏆 コレクション達成率: {percent}%（{owned}/{total}）",
    "shop.petTip": "クリックで動くよ",
    "shop.alert.notEnough": "通貨が足りません。",
    "shop.alert.alreadyOwned": "既に所持しています。",
    "shop.alert.loginNeeded": "ログインしてください。",
    "shop.alert.buyLoginNeeded": "購入にはログインが必要です。",
    "shop.buying": "購入中...",
    "shop.purchased": "「{name}」を購入しました！",
    "shop.buyFailed": "購入に失敗しました（{msg}）",

    // --- ランキング（ranking-page.js） ---
    "rank.title": "📊 ランキング",
    "rank.cat.winRate": "勝率",
    "rank.cat.wins": "勝利数",
    "rank.cat.matches": "対戦数",
    "rank.value.winRate": "{v}%",
    "rank.value.wins": "{v}勝",
    "rank.value.matches": "{v}戦",
    "rank.empty": "まだ対象のプレイヤーがいません。",
    "rank.rules.title": "ランキングのルール",
    "rank.rules.b1": "・勝率TOP3ランキングは、対戦経験が極端に少ないプレイヤーが数試合だけで上位に入ってしまわないように、実際に対戦したことがあるプレイヤーの「平均対戦数」の50%を超える対戦数のプレイヤーのみが対象になります。",
    "rank.rules.border": "現在の実対戦者の平均対戦数: {average}回 → 参加基準(ボーダー): {border}回を超える対戦数",
    "rank.rules.b2": "・同順位の決め方: ①勝率 → ②勝利数 → ③対戦数 の順で比較し、すべて同じ場合は同順位として併記します。",
    "rank.rulesBtnTip": "ランキングのルールを見る",
    "rank.loading": "読み込み中…",
    "rank.loadFail": "ランキングの取得に失敗しました。通信環境を確認してください。",
    "rank.iconTip": "ランキングを開きます",
    "rank.iconCaption": "ランキング",
    "rank.iconDetail": "勝率・勝利数・対戦数のランキングを確認できます。",

    "phase.titleSuffix": "{label}フェイズ",

    // --- 対局中の通知・演出（フェイズ6。turn-announce / hand-announcer / victory /
    //     contact-approval / final-lock-approval / gate-invasion-modal） ---
    "game.you": "あなた",
    "game.seat": "プレイヤー{seat}",
    // --- フェーズ7: 対局中のモーダル・案内文（main.js） ---
    "game.effectOf": "「{card}」の効果",
    "game.thisCard": "このカード",
    "game.ritual.toPlayer": "{name}に",
    "game.ritual.fromXtoY": "{actor}が{target}から",
    "game.ritual.fromPlayer": "{name}から",
    "game.pick.fromHand": "{name}の手札から1枚選んでください",
    "game.pick.fromHandFaceDown": "{name}の手札（裏向き）から1枚選んでください",
    "game.pick.randomFromHand": "{name}の手札（裏向き）から無作為に1枚選んでください",
    "game.ritual.receivedFrom": "{name}から受け取りました",
    "game.ritual.gaveTo": "{name}に渡しました",
    "game.ritual.aboutToSteal": "{name}の手札から、奪う{n}枚をこれから選びます。",
    "game.ritual.pickN": "奪うカードを{n}枚選んでください（{sel}/{n}）",
    "game.ritual.confirmN": "✅ 決定（{sel}/{n}枚）",
    "game.ritual.pickStealFaceDown": "{name}の手札（裏向き）から奪うカードを選んでください（{i}/{n}）",
    "game.ritual.attackerTakes": "{name}があなたの手札から{n}枚を奪います…",
    "game.ritual.tapToFlip": "タップして、奪う{n}枚をめくろう…",
    "game.ritual.pickOneFaceDown": "{name}の手札（裏向き）から奪う1枚を選んでください",
    "game.ritual.pickOneFor": "{attacker}が、{defender}の手札（裏向き）から奪う1枚を選んでください",
    "game.choice.chose": "{name}が「{label}」を選びました。",
    "game.choice.made": "{name}が選択しました。",
    "game.declare.byPlayer": "{name}が宣言",
    "game.declare.exact": "色を{n}色宣言してください",
    "game.declare.atLeast": "{n}色以上、色を宣言してください",
    "game.slum.discardTo3": "手札が3枚になるまで捨ててください（あと{n}枚）",
    "game.waitingChoice": "{name}さんの選択を待っています…",
    "game.confirm.lockCard": "{card}をロックしますか？",
    "game.confirm.useCard": "{card}を使用しますか？",
    "game.anytime.haveNamed": "{name}：いつでも使えるカードがあります",
    "game.cpuStepHint": "▶ クリックして次へ",
    "game.handEffect.notUsable": "「{card}」は手札効果を使えないカードです。",
    "game.contactResult.tookFrom": "{name}から「{card}」を奪いました！",
    "game.contactResult.nothingToTake": "{name}の手札が無く、何も奪えませんでした。",
    "game.contactResult.lostTo": "{name}に「{card}」を奪われました…",
    "game.contactResult.nothingLost": "{name}に接触されましたが、手札が無く何も奪われませんでした。",
    "game.brand.locked": "{name}が{brand}の色のロックエリアにロックしました。{brand}の効果で手札を2枚捨てます。",
    "game.brand.pickDiscard": "{brand}：捨てる手札を選択してください",
    "game.brand.pickCell": "{brand}を裏向きで置くマスを選択してください",
    "game.brand.placed": "{brand}を盤面{where}に裏向きで置きました。",
    "game.brand.placedAt": "の{coord}",
    "game.brand.drawAskN": "🖋 {brand}：ロックしなかったので、烙印{total}枚のうち{i}枚目のドローができます。ドローしますか？（任意）",
    "game.brand.drawAsk1": "🖋 {brand}：ロックしなかったので1枚ドローできます。ドローしますか？（任意）",
    "game.brand.drewBecauseNoLock": "{name}はロックしなかったので、{brand}の効果で1枚ドローしました。",
    "game.myDeck.drewAnnounce": "{name}がマイデッキから1枚ドローしました。",
    "game.counterLock.cancelled": "{defender}のカウンターロックで、{attacker}の接触は無効になりました。",
    "game.pileTooltip": "{label}　{n}枚",
    "game.pileTooltipDiscard": "{label}　{n}枚（ダブルタップで捨て札一覧）",
    "game.handTooltip": "{name}　手札{n}枚",
    "game.discardBar": "捨て場 {n}",
    "game.stack.title": "重なっているカード（{n}枚・下から上の順）",
    "game.discardList.titleN": "捨て札一覧（{n}枚・上から順）",
    "game.gomennasai.blocks": "{name}はゴメンナサイを使い、{attacker}のロックを1枚奪って最後のロックを阻止します！",
    "game.gomennasai.tookFrom": "{name}が{attacker}のロックエリアから奪いました",
    "game.autoToggle.title": "⚙️ {name} さんが自動処理モードを{state}にすることを提案中！",
    "game.autoToggle.needYou": "あなた（{name}）の承認が必要です",
    "game.autoToggle.waiting": "{name} さんの承認を待っています…",
    "game.autoToggle.approve": "✅ 承認する",
    "game.autoToggle.reject": "🚫 却下する",
    "game.log.arrival": "「{card}」の到達効果を得ました{where}",
    "game.log.coordSuffix": "（{coord}）",
    "game.log.handEffect": "「{card}」の手札効果を得ました",
    "game.log.lockedCard": "「{card}」をロックしました",
    "game.log.declared": "色を宣言しました：{colors}",
    "game.log.brandDrawN": "誘惑の黒の烙印の効果で1枚ドローしました（{i}枚目）",
    "game.log.placedNamed": "「{card}」を{fd}置きました{where}",
    "game.log.placedCard": "カードを{fd}置きました{where}",
    "game.log.turnOf": "{name}のターン",
    "game.turnRound": "ターン {turn} ／ ラウンド {round}",
    "game.unlinked": "未連携",
    "game.shop.buyFor": "🔒 {cost}で購入",
    "game.self.meSuffix": "{name}（自分）",
    "game.self.handCount": "手札：{n}枚",
    "game.pile.deck": "山札",
    "game.pile.eternal": "エターナルカード",
    "game.pile.first": "ファーストカード",
    "game.pile.discard": "捨て場",
    "game.btn.publicDraw": "🎴 公開ドロー",
    "game.btn.declare": "📣 宣言",
    "game.btn.discard": "🗑 捨てる",
    "game.cpuOperating": " 🤖CPU操作中",
    "game.ritual.shuffling": "シャッフル中…",
    "game.ritual.opponentPicking": "相手があなたの手札から1枚選んでいます…",
    "game.ritual.stolenTheseCards": "これらのカードが奪われました！",
    "game.ritual.stolenThisCard": "このカードが奪われました！",
    "game.ritual.tookIt": "奪いました！",
    "game.label.took": "奪った",
    "game.label.wasTaken": "奪われた",
    "game.label.received": "受け取った",
    "game.label.handedOver": "渡した",
    "game.label.stepped": "踏んだ",
    "game.label.collected": "回収した",
    "game.label.madeDiscard": "捨てさせた",
    "game.label.forcedDiscard": "捨てさせられた",
    "game.label.gambleReveal": "ギャンブル公開",
    "game.label.reveal": "公開",
    "game.ritual.gateSuccess": "🚩 ゲート侵攻成功！",
    "game.ritual.pickStealBtn": "奪う札を選ぶ",
    "game.ritual.onlyOneCard": "手札はこの1枚だけです。スリカエは必ず1枚ずつの交換なので、このカードを相手へ返してください",
    "game.ritual.giveCard": "相手に渡すカードを手札から選択してください",
    "game.ritual.stealFailed": "通信エラーで相手の手札を奪えなかったため、交換を中止しました。もう一度お試しください。",
    "game.pick.emptyCell": "何もないマスを選択してください",
    "game.pick.moveTo": "移動先のマスを選択してください",
    "game.pick.cellWithCardToHand": "手札に加えるカードのあるマスを選択してください",
    "game.pick.openCell1": "オープンするカードのあるマスを選択してください（1/2）",
    "game.pick.openCell2": "オープンするカードのあるマスを選択してください（2/2）",
    "game.pick.placeFromHand": "そのマスに置くカードを手札から選択してください",
    "game.pick.cannotPickCell": "そのマスは選べません。",
    "game.pick.thisCard": "このカードを選びますか？",
    "game.pick.lockSlotCard": "このスロットのカード（使うカードを選んでください）",
    "game.pick.handPhaseCard": "ハンドフェイズで使うカードを選んでください",
    "game.pick.stackedCard": "使うカードを選んでください（下から上の順）",
    "game.pick.noMore": "これ以上選ばない",
    "game.pick.lockTarget": "ロックする手札を選択してください",
    "game.pick.lockSlot": "ロックする場所を選択してください",
    "game.pick.stealLock": "奪うロックカードを選択してください",
    "game.pick.discardPurple": "捨てる紫のカードを手札から選択してください",
    "game.place.where": "どこから置きますか？",
    "game.place.fromDeckBtn": "🂠 山札から",
    "game.place.fromHandBtn": "🖐 手札から",
    "game.place.fromDeck": "山札から",
    "game.place.fromHand": "手札から",
    "game.place.deckFaceDown": "山札から１枚を裏向きで置く",
    "game.place.handFaceDown": "手札から１枚を裏向きで置く",
    "game.place.noHandSoDeck": "手札がないため山札から置く",
    "game.party.move": "１マス移動し、移動先の到達効果は得ない。",
    "game.party.pickup": "場の任意の１枚をあなたの手札に加える。",
    "game.party.openTwo": "場の任意の２枚をオープンする。",
    "game.declare.viewBoard": "盤面を見る",
    "game.declare.viewingBoard": "盤面を確認中…クリックで選択画面に戻ります",
    "game.declare.submit": "宣言する",
    "game.color.red": "赤",
    "game.color.orange": "橙",
    "game.color.yellow": "黄",
    "game.color.green": "緑",
    "game.color.blue": "青",
    "game.color.pink": "桃",
    "game.color.purple": "紫",
    "game.fizzle.toHand": "不発のため、このカードを手札に加えます。",
    "game.fizzle.nothing": "不発のため、何も起きませんでした。",
    "game.handEffect.onlyHandPhase": "このカードの効果は、あなたのハンドフェイズ（自分のターン）に使えます。",
    "game.handEffect.noCost": "捨てられる同じ色のカードが手札にありません。",
    "game.handEffect.cantUseNow": "今はこのカードの効果を使えません。",
    "game.handEffect.dropToUse": "そのカードを場にドロップすると、手札効果が発動します。",
    "game.handEffect.noMoveThisTurn": "禁断の果実 マルメゴで橙が出たため、このターンは移動できません（接触は可能です）。",
    "game.anytime.resumeBtn": "🔔 割り込みモーダル再開",
    "game.anytime.resumeTip": "「今後このモーダルを出さない」を選んだ後、いつでも使える効果の割り込みモーダルをまた表示させます。",
    "game.anytime.have": "いつでも使えるカードがあります",
    "game.anytime.use": "使う",
    "game.anytime.never": "今後このモーダルを出さない",
    "game.confirm.yes": "✅ はい",
    "game.confirm.no": "🚫 いいえ",
    "game.confirm.yesPlain": "はい",
    "game.confirm.noPlain": "いいえ",
    "game.confirm.never": "今後このモーダルを表示しない",
    "game.confirm.cancel": "キャンセル",
    "game.confirm.close": "閉じる",
    "game.contactResult.title": "🤝 接触の結果",
    "game.contact.reallyQ": "本当に接触しますか？",
    "game.contact.requestBtn": "🤝 接触を申し込む",
    "game.contact.doBtn": "🤝 接触する",
    "game.counterLock.askLock": "🛡️ カウンターロックの効果で、手札を1枚ロックエリアにロックしますか？（任意）",
    "game.counterLock.lock": "ロックする",
    "game.counterLock.dont": "しない",
    "game.brand.name": "誘惑の黒の烙印",
    "game.brand.draw": "ドローする",
    "game.brand.dont": "しない",
    "game.brand.drewOne": "誘惑の黒の烙印の効果で1枚ドローしました",
    "game.myDeck.drewOne": "マイデッキから1枚ドローしました",
    "game.gomennasai.blockBtn": "相手の最後のロックを阻止する",
    "game.gomennasai.reason": "「ゴメンナサイッ！」でロックから奪取",
    "game.gomennasai.costFailed": "追色コストを捨てられませんでした（通信エラーの可能性）。もう一度「ゴメンナサイを使う」を押してください。",
    "game.gateAuto.title": "ゲート侵攻ボーナス",
    "game.gateAuto.body": "相手ゲート侵攻ボーナスの発生条件を満たしています。自動で処理しますか？",
    "game.gateAuto.manual": "いいえ（自分で処理する）",
    "game.gateAuto.auto": "自動で処理する",
    "game.gateAuto.happened": "ゲート侵攻が発生しました",
    "game.gate.collectedOwn": "自分のゲートから回収しました",
    "game.open.yes": "👁 オープンする",
    "game.open.no": "🚫 オープンしない",
    "game.menu.cardNote": "カード補足を見る",
    "game.menu.stackedCards": "重なっているカードを見る",
    "game.menu.cardBack": "カード裏面デザインを変更",
    "game.menu.deckList": "山札一覧を見る",
    "game.menu.discardList": "捨て札一覧を見る",
    "game.menu.pieceSkin": "駒スキンを変更",
    "game.menu.hideLockBar": "ロックエリアバーを隠す",
    "game.menu.hideLockBarDone": "ロックエリアバーを隠しました",
    "game.menu.hideLockBarHint1": "画面右上の「⚙ オプション」→「基本設定」の「ロックエリアバーを表示する」を",
    "game.menu.hideLockBarHint2": "チェックすると、いつでも元に戻せます。",
    "game.menu.playmat": "プレイマットを変更",
    "game.menu.background": "背景画像を変更",
    "game.stack.noNote": "（補足なし）",
    "game.discardList.title": "捨て札一覧",
    "game.discardList.empty": "捨て札はありません。",
    "game.spectate.leave": "観戦をやめる",
    "game.spectate.all": "👀 観戦中（すべて見える）",
    "game.spectate.public": "👀 観戦中（公開情報のみ）",
    "game.log.title": "📜 行動ログ",
    "game.log.howToTitle": "📜 行動ログの見かた",
    "game.log.howToBtn": "行動ログの見かた",
    "game.log.h1": "新しい行動ほど上に表示されます。ラウンド（R）・ターン（T）ごとに区切られ、手番のプレイヤーはアバターと色で示されます。",
    "game.log.h2": "記録される内容：カードの到達効果、手札効果、色の宣言、ゲート侵攻 など。",
    "game.log.h3": "マス座標（例：C3）は盤面の絶対座標です。列は左から A・B・C…G、行は上から 1・2・3…7。C3 なら「左から3列目・上から3行目」のマスを指します（盤面の向きは各プレイヤーで回転しますが、座標は共通の基準です）。",
    "game.log.h4": "同じ内容が連続したときはまとめて1行にしています。",
    "game.log.empty": "（まだ記録がありません）",
    "game.log.toggleTip": "行動ログの表示／非表示（離席復帰時の見返し用）",
    "game.log.caption": "ログ",
    "game.log.bullet": "・",
    "game.log.lockArea": "（ロックエリア）",
    "game.log.faceDown": "裏向きで",
    "game.online.title": "オンライン対戦",
    "game.online.help1": "ログインすると、離れた場所にいる友達と部屋を作って対局できます（ログアウト中/ログイン中/入室中の3つの状態をアイコンで表します）。",
    "game.online.help2": "入室中は、アイコンの下に部屋名が小さく表示されます。クリックすると部屋の詳細（参加人数・退室等）を開けます。",
    "game.online.inRoomTip": "オンライン対戦中です。クリックで部屋の詳細を開きます",
    "game.online.signedInTip": "ログイン中です。クリックでオンライン対戦の部屋一覧を開きます",
    "game.online.signedIn": "ログイン中",
    "game.online.signInTip": "オンライン対戦を始めるにはログインしてください",
    "game.online.caption": "オンライン",
    "game.self.emote": "クリックしてエモートを選ぶ",
    "game.self.pieceSkin": "クリックして駒スキンを変更",
    "game.self.cardBack": "クリックしてカード裏面を変更（自分の画面にだけ反映されます）",
    "game.self.playmat": "クリックしてプレイマットを変更",
    "game.self.background": "クリックして背景画像を変更",
    "game.self.pet": "クリックしてペットを変更",
    "game.self.name": "クリックして名前を変更",
    "game.self.titleTip": "マイページの「称号」から変更できます",
    "game.self.handCountLabel": "手札の枚数",
    "game.self.me": "自分",
    "game.bug.tip": "不具合報告（コメント＋ログを送信）",
    "game.bug.caption": "不具合報告",
    "game.profile.title": "🎉 プロフィールの確認",
    "game.profile.body": "ニックネームとアバターを決めましょう（あとから変更できます）。",
    "game.profile.nickname": "ニックネーム",
    "game.profile.nicknamePh": "ニックネームを入力",
    "game.profile.start": "この内容で始める",
    "game.profile.pickAvatar": "アバターを選択",
    "game.profile.useGoogle": "Googleのプロフィール画像を使う",
    "game.profile.useUpload": "アップロードした画像を使う",
    "game.profile.protagonist": "記憶を失った青年（駒の色に合わせて色が変わります）",
    "game.afk.substituting": "🤖 CPUに切替中です（放置のため自動操作中）。",
    "game.afk.resume": "復帰する",
    "game.afk.opponentLost": "相手が放置により敗北したため、あなたの勝ちです。",
    "game.afk.youLost": "放置（時間切れが続いた）ため、あなたの敗北です。",
    "game.afk.alreadyWon": "この対局は既に終了しています（あなたの勝ち）。",
    "game.afk.alreadyLost": "放置（時間切れが続いた）ため、あなたの敗北で確定しています。",
    "game.room.closed": "この対局は終了しました（部屋が閉じられました）。ホームに戻ります。",
    "game.loginBonus.title": "🎁 ログインボーナス",
    "game.loginBonus.body": "今日もあそんでくれてありがとう！（ログインボーナスは1日1回）",
    "game.loginBonus.claim": "受け取る",
    "game.myDeck": "マイデッキ",
    "game.pickup.fromDiscard": "捨て場から取得",
    "game.pickup.fromDeck": "山札から引いた",
    "game.turnOf": "{name} のターン",
    "game.victory.title": "{name} の勝利！",
    "game.victory.sub": "7色すべてのカードをロックエリアに揃えました",
    // 中央フラッシュ（獲得・ドロー・ロック・捨て・ゲート侵攻）
    "game.toast.hiddenGain": "{name}が非公開のカードを{n}枚手札に加えました",
    "game.toast.gained": "{name}が獲得",
    "game.toast.hiddenNote": "＋非公開のカード{n}枚",
    "game.toast.gateTitle": "相手ゲート侵攻ボーナス発生",
    "game.toast.gateText": "{attacker}が{defender}のゲートに侵攻！",
    "game.toast.draws": "{name}が{n}枚ドローします",
    "game.toast.locked": "{name}がロック",
    "game.toast.discarded": "{name}が捨てました",
    // 右下「このターンの出来事」のチップ（ツールチップ文言）
    "game.chip.gainedN": "{name}が{n}枚獲得",
    "game.chip.gained": "{name}が獲得",
    "game.chip.gate": "{name}がゲート侵攻",
    "game.chip.draw": "{name}が{n}枚ドロー",
    "game.chip.lock": "{name}がロック（{card}）",
    "game.chip.discard": "{name}が捨てた（{card}）",
    "game.chip.reason": "（{reason}）",
    "game.chip.reasonSlash": "／{reason}",
    // 接触（contact-approval.js）
    "game.contact.title": "🤝 接触の申し込み",
    "game.contact.bodyCounter": "{attacker}があなた（{defender}）に接触を申し込んでいます。あなたは「カウンターロック」を持っています。使いますか？（使うとこの接触は無効になります）",
    "game.contact.bodySelf": "{attacker}があなた（{defender}）に接触を申し込んでいます。承認すると、手札から無作為に1枚渡し、あなたは自分のゲートへ強制移動します。",
    "game.contact.bodyWait": "{attacker}が{defender}に接触を申し込み中… 相手の承認を待っています。",
    "game.contact.useCounter": "🛡️ カウンターロックを使う",
    "game.contact.declineCounter": "使わない（承認する）",
    "game.contact.approve": "✅ 承認する",
    "game.contact.reject": "🚫 拒否する",
    // 最後のロックの承認（final-lock-approval.js）
    "game.finalLock.gomennasaiTitle": "🍬 ゴメンナサイ",
    "game.finalLock.gomennasaiPick": "ロックエリアから奪うカードを選んでください",
    "game.finalLock.title": "🔒 {name} さんが最後のロックに挑戦中！",
    "game.finalLock.needYou": "あなた（{name}）の承認が必要です",
    "game.finalLock.waiting": "{name} さんの承認を待っています…",
    "game.finalLock.approve": "✅ 承認する",
    "game.finalLock.useGomennasai": "🍬 ゴメンナサイを使う",
    // ゲート侵攻の演出（gate-invasion-modal.js）
    "game.gate.title": "相手ゲート侵攻ボーナス",
    "game.gate.skip": "スキップ",
    "game.gate.hiddenNote": "＋非公開のカード{n}枚",
    "game.gate.step.invade": "{attacker}が{defender}のゲートに侵攻！",
    "game.gate.step.stealIntro": "{attacker}はゲート侵攻成功！\n{defender}の手札{n}枚を無作為に奪います。",
    "game.gate.step.stealDone": "{attacker}は{defender}の手札{n}枚を奪いました。",
    "game.gate.step.stealNone": "{attacker}はゲート侵攻成功！\n{defender}の手札枚数が半分未満のため、奪えるカードはありません。",
    "game.gate.step.eternal": "{attacker}はエターナルカード「{card}」を獲得！\n自分のロックエリアにロックします。",
    "game.gate.step.eternalPushed": "ロックスロットにあったカードが弾き出され、{attacker}の手札に加わりました。",
    "game.gate.step.eternalEmpty": "{attacker}はエターナルカードを獲得するはずでしたが、盤面の外のエターナルカードはもう残っていません。",
    "game.gate.step.returnHomeCards": "{attacker}は自分のゲートにあるカードをすべて回収し、ゲートに帰還します。",
    "game.gate.step.returnHome": "{attacker}は自分のゲートに帰還します。",
    "game.gate.reason.steal": "相手ゲート侵攻ボーナス（手札を奪う）",
    "game.gate.reason.bumped": "相手ゲート侵攻ボーナス（ロックから押し出された）",
    "game.gate.reason.collected": "相手ゲート侵攻ボーナス（自分のゲートから回収）",
  },
  en: {
    // --- Home screen ---
    "home.subtitle": "Home",
    "home.tile.tutorial": "Story Tutorial",
    "home.tile.match": "CPU & Friendly Match",
    "home.tile.ranked": "Free Match (Ranked)",
    "home.tile.shop": "Shop",
    "home.tile.ranking": "Rankings",
    "home.tile.mypage": "My Page / Deck Editor",
    "home.tile.codex": "Codex / Rulebook",
    "home.tile.news": "News / Updates",
    "home.comingSoon": "“{label}” is coming soon. Stay tuned!",
    "home.comingSoonBadge": "Coming soon",
    "home.newBadge": "NEW",
    "home.matchChoice.title": "Choose a match mode",
    "home.matchChoice.friendly": "Friendly Match",
    "home.matchChoice.friendlyDesc": "Play online (create or join a room)",
    "home.matchChoice.cpu": "CPU Match (solo)",
    "home.matchChoice.cpuDesc": "Play against the CPU on this device (no login)",
    "home.matchChoice.difficultyLabel": "🤖 CPU strength (CPU match only)",
    "home.matchChoice.difficultyHint": "Rookie = random / Intermediate & Advanced = smart AI / Master = peeks at face-down cards",
    "home.matchChoice.countLabel": "👥 Players (CPU match only)",
    "home.matchChoice.countHint": "You + CPU (3 / 4 players add 2 / 3 CPUs)",
    "home.rankLabel": "Your rank",
    "home.rankAboutTitle": "About ranked play",
    "home.waitingBadge": "🟢 {count} looking for a match!",
    "common.back": "← Back",
    // --- CPU strength / player count (shared home / options) ---
    "cpu.diff.rookie": "Rookie",
    "cpu.diff.intermediate": "Intermediate",
    "cpu.diff.advanced": "Advanced",
    "cpu.diff.master": "Master",
    "cpu.count.2": "2 players",
    "cpu.count.3": "3 players",
    "cpu.count.4": "4 players",
    // --- Options ---
    "opt.title": "Options",
    "opt.basicSettings": "Settings",
    "opt.detailSettings": "More settings",
    "opt.detailSettingsHint": "Look & feel, performance, CPU matches, notifications, shortcuts…",
    "opt.backToBasic": "← Back to settings",
    "opt.reset": "Reset",
    "opt.soundVolume": "Sound effects volume",
    "opt.bgmVolume": "Music volume",
    "opt.langNote": "Currently only card text is translated (menus are being localized).",
    "opt.cardPreviewSize": "Card zoom size",
    "opt.cardPreviewSide": "Card zoom direction",
    "opt.cpuSpeed": "CPU speed",
    "opt.cpuStrength": "CPU strength",
    "opt.resetAccount": "Reset account settings",
    "opt.resetAccountDesc": "Restores name, avatar, piece skin, playmat, card back and background to defaults.",
    "opt.resetAccountConfirm": "Really reset? (click again)",
    "opt.resetAccountBusy": "Resetting…",
    "opt.resetAccountFailed": "Reset failed",
    "opt.statsLink": "🏆 Link a Battle Record player",
    "opt.statsLinkSelect": "Select",
    "opt.statsLinkDone": "✅ Linked",
    "opt.statsLinkGoogleOnly": "You must be signed in with Google to link.",
    "opt.statsLinkReloginGoogle": "Sign in again with Google",
    "opt.pressKey": "Press a key…",
    "opt.sec.group.volume": "Volume",
    "opt.sec.group.display": "Display & Effects",
    "opt.sec.group.autoTimer": "Auto-processing & Timer",
    "opt.sec.group.common": "Everyday settings",
    "opt.sec.group.heavy": "If the game feels slow or stutters",
    "opt.sec.group.look": "How things look",
    "opt.sec.group.auto": "Play card effects automatically",
    "opt.sec.group.advanced": "Testing & advanced",
    "opt.chk.boardIllustOnly": "Show board cards as artwork only (easier to tell apart from afar; hand & zoom unchanged)",
    "opt.chk.fixedHand": "Always keep my hand at the bottom of the screen (stays visible when you zoom the board)",
    "opt.chk.flatten2d": "Show the board flat in 2D (use this if the screen flickers on a tablet)",
    "opt.chk.fullscreen": "Play in fullscreen (hides browser tabs and address bar)",
    "opt.chk.opponentBaseTimer": "Also show opponents' remaining time",
    "opt.chk.actionConfirm": "Ask before locking or using a card (prevents mis-taps)",
    "opt.sec.lockArea": "Lock Area",
    "opt.chk.lockAreaBar": "Show the Lock Area bar",
    "opt.chk.lockColor": "Tint the Lock Area with its colors",
    "opt.sec.modalDuration": "How long notices stay on screen",
    "opt.sec.reduceAnim": "Reduce animations (if performance is poor)",
    "opt.chk.disableFlight": "Stop pieces and cards from flying across the board",
    "opt.chk.disableArrival": "Stop the arrival / lock light effects",
    "opt.chk.disableGlow": "Stop always-on glowing effects (turn glow, hourglass rope, etc.)",
    "opt.chk.cpuAutoAdvance": "Auto-advance CPU result notices (off = shows until clicked)",
    "opt.rankedAutoFixed": "Auto-processing is always ON in ranked matches.",
    "opt.autoProcessing": "Auto-process card effects",
    "opt.emergencyEndTurn": "🚨 Emergency end turn",
    "opt.sec.cpuBattle": "CPU Match (solo)",
    "opt.sec.rankedNotify": "Ranked match notifications",
    "opt.sec.shortcuts": "Shortcut keys (player buttons)",
    "opt.shortcutRecommended": "⭐ Recommended",
    "opt.adminMode": "⚙ Admin mode",
    "opt.notify.enable": "Notify me when an opponent appears",
    "opt.notify.timeLabel": "Allowed notification hours",
    "opt.notify.hint": "Same start and end = all day. Start > end wraps overnight (e.g. 22:00–6:00).",
    // --- In-game buttons ---
    "btn.endTurn.caption": "End turn",
    "btn.endTurn.detail1": "Ends your turn and passes play to the next player.",
    "btn.endTurn.detail2": "If your piece is on an opponent's Gate, the “Gate Invasion Bonus” is processed automatically when your turn ends.",
    "btn.endTurn.otherTurn": "It's {name}'s turn now",
    "btn.endTurn.otherPriority": "{name} has priority now",
    "btn.endTurn.tooltipSelf": "End your turn",
    "btn.endTurn.tooltipLocal": "End {name}'s turn",
    "btn.boardZoom.caption": "Zoom board",
    "btn.boardZoom.label0": "Zoom in",
    "btn.boardZoom.label1": "Zoom more",
    "btn.boardZoom.label2": "Reset",
    "btn.boardZoom.returnToView": "Reset view",
    "btn.boardZoom.detail1": "Zooms the whole board for easier viewing. Until you register a view, each press cycles “Zoom in” → “Zoom more” → “Reset”.",
    "btn.boardZoom.detail2": "Once you use free zoom (mouse wheel) or pan (middle-click drag), this becomes a “Reset view” button. While active, a blinking “Register zoom” button appears — press it to save the current view. After that, pressing this button from the normal view jumps straight to your saved view.",
    "btn.handShuffle.caption": "Shuffle hand",
    "btn.handShuffle.tooltip": "Shuffles the order of your hand (the cards themselves don't change)",
    "btn.handShuffle.detail1": "Shuffles only the order of your hand. The cards you hold do not change.",
    "btn.handShuffle.detail2": "A cosmetic effect to make it harder for opponents to guess your hand.",
    "btn.draw.caption": "Draw 1",
    "btn.draw.tooltip": "Draw 1 card from the deck into your hand",
    "btn.draw.detail1": "Draws the top card of the deck into your hand.",
    "btn.draw.detail2": "If the deck runs out, the discard pile becomes the new deck face-down (no shuffle).",
    "btn.publicDraw.caption": "Open draw",
    "btn.publicDraw.tooltip": "Draw 1 card from the deck face-up (open)",
    "btn.publicDraw.detail1": "Draws the top card of the deck and lays it face-up near your hand (it does not go directly into your fan of cards).",
    "btn.publicDraw.detail2": "Pressing “Shuffle hand” or “End turn” merges the open-drawn cards into your normal hand.",
    // --- Phase guide (shared with tutorial / help) ---
    "phase.titleSuffix": "{label} Phase",
    "phase.lock.label": "Lock",
    "phase.lock.short": "You may lock one card from your hand (optional)",
    "phase.lock.d1": "You may lock exactly one card from your hand (or none).",
    "phase.lock.d2": "A locked card generally leaves your hand and its Hand Effect can't be used (exception: First and Eternal cards' Hand Effects can still be used).",
    "phase.hand.label": "Hand",
    "phase.hand.short": "You may use any number of hand cards (optional)",
    "phase.hand.d1": "You may use any number of cards from your hand (or none). A Hand Effect is gained by discarding that card itself.",
    "phase.hand.d2": "Except when using them, keep your hand hidden from opponents. There is no hand-size limit.",
    "phase.move.label": "Move",
    "phase.move.short": "You must do either “Move” or “Contact”",
    "phase.move.d1": "In the Move phase, you must do exactly one of the following.",
    "phase.move.d2": "🚶 Move: place your piece on an adjacent space (up/down/left/right) that has only a card.",
    "phase.move.d3": "　If the card is face-down it flips; if face-up its Arrival Effect triggers and the card generally goes to your hand.",
    "phase.move.d4": "　You cannot move onto a space occupied by an opponent's piece.",
    "phase.move.d5": "🤝 Contact: choose an adjacent opponent's piece and take one card at random from that opponent's hand.",
    "phase.move.d6": "　The contacted opponent is forced back to their Gate (you yourself don't move).",
    "phase.move.d7": "📥 If there is neither a card nor an opponent's piece adjacent: place one card face-up from the deck on any adjacent space and end your turn.",
    "phase.autoSkip.caption": "Auto-advance",
    "phase.autoSkip.on": "ON",
    "phase.autoSkip.off": "OFF",
    "phase.autoSkip.titleOn": "Phase auto-advance: ON (phases with nothing to do are skipped automatically)",
    "phase.autoSkip.titleOff": "Phase auto-advance: OFF (phases don't advance until you press skip; opponents can't tell you have no lockable cards, etc.)",

    // --- Opening / login screen ---
    "opening.loginToggle": "Log in",
    "opening.testMode": "Test mode",
    "opening.testMode.tip": "Go straight to a sandbox board where you can move all players on one screen (for development/testing).",
    "opening.adminPanel": "🔧 Admin panel",
    "opening.adminPanel.tip": "Open admin mode (settings, usage stats, user list, etc.).",
    "opening.versionTip": "App version (deploy date/time)",
    "opening.clickToClose": "Click to close",
    "opening.clickToSkip": "Click to skip",
    "opening.localPlay": "Play locally (no login)",
    "opening.onlineLoadFail": "Couldn't load online features. You can still play locally.",
    "opening.loggedInTitle": "🌐 Logged in ({name})",
    "opening.continueOnline": "Continue online",
    "opening.logout": "Log out",
    "opening.testModeHint": "🧪 Test mode: after logging in, you'll go straight to the sandbox board without the “Continue online” step. To play a normal online match, close with the ✕ at the top right.",
    "opening.googleLogin": "Log in with Google",
    "opening.error": "Error: {msg}",
    "opening.googleInfo.title": "Benefits of logging in with an account",
    "opening.googleInfo.b1": "Settings like your name, avatar, and piece skin carry over even when you log in from another device or browser.",
    "opening.googleInfo.b2": "Your link to a player in the match-record system is also saved to your account, so you won't have to pick it again next time you log in.",
    "opening.googleInfo.b3": "Unlike guest login, you can keep playing as the same account even after logging out or switching devices.",
    "opening.guestLogin": "Log in as guest",
    "opening.loggingIn": "Logging in...",
    "opening.guestInfo.title": "About guest login",
    "opening.guestInfo.b1": "No email registration or confirmation needed — you can join online matches right away.",
    "opening.guestInfo.b2": "However, once you log out or access from another device or browser, you can't return to the same account (there is currently no way to carry over a guest account later).",
    "opening.guestInfo.b3": "If you plan to play often, or want to keep your name, avatar, piece skin, and other settings long-term, we recommend logging in with Google above.",
    "opening.guestConfirm.title": "⚠️ Before logging in as a guest",
    "opening.guestConfirm.body": "Guest login can't join rankings or remember settings like your name, avatar, or piece skin. Also, once you log out or access from another device or browser, you can never return to this account.",
    "opening.guestConfirm.yes": "Start as guest anyway",
    "opening.guestConfirm.no": "Cancel",
    "opening.moreLogin.closed": "Other login methods (email) ▾",
    "opening.moreLogin.open": "Other login methods (email) ▴",
    "opening.emailPlaceholder": "Email address",
    "opening.sendMagicLink": "Send magic link",
    "opening.sending": "Sending...",
    "opening.checkEmail": "Check your email and open the link we sent.",
    // Opening story crawl (blank lines stay "")
    "opening.story.1": "A world apart: “Farbend.”",
    "opening.story.2": "A world once brimming with color.",
    "opening.story.3": "Seven nations dwell in this world,",
    "opening.story.4": "each ruling over its own color,",
    "opening.story.5": "and in balance they built a lasting peace.",
    "opening.story.6": "But then, all at once, the world's color——",
    "opening.story.7": "vanished.",
    "opening.story.8": "Each nation held a national treasure:",
    "opening.story.9": "a “Cube” clad in that nation's color.",
    "opening.story.10": "Yet for some reason, those Cubes alone",
    "opening.story.11": "never lost their color.",
    "opening.story.12": "In a world drained of color, the people lost their radiance and despaired.",
    "opening.story.13": "In time, the kings of each nation",
    "opening.story.14": "discovered the Cubes' “special power.”",
    "opening.story.15": "It was the power to give color form.",
    "opening.story.16": "Color is intertwined with",
    "opening.story.17": "everything in this world—",
    "opening.story.18": "objects, memories, abilities, all of it.",
    "opening.story.19": "One day, a Cube's power spoke to a king:",
    "opening.story.20": "—Gather the seven colors.—",
    "opening.story.21": "What happens when all seven are gathered?",
    "opening.story.22": "As each nation's ambition, scheme, and ideal collide,",
    "opening.story.23": "the battle over the seven colors",
    "opening.story.24": "begins now.",

    // --- Shop ---
    "shop.title": "Shop",
    "shop.cat.pieceSkin": "🎲 Piece skins",
    "shop.cat.cardBack": "🂠 Card backs",
    "shop.cat.playmat": "🟩 Playmats",
    "shop.cat.background": "🖼️ Backgrounds",
    "shop.cat.pet": "🐾 Pets",
    "shop.cat.avatar": "😀 Avatars",
    "shop.cat.mydeck": "🃏 Deck slots",
    "shop.ribbon.free": "Free",
    "shop.ribbon.owned": "Owned",
    "shop.balance.loginPrompt": "Log in to earn currency",
    "shop.balance": "Balance: 🪙 {n}",
    "shop.completion": "🏆 Collection: {percent}% ({owned}/{total})",
    "shop.petTip": "Click to make it move",
    "shop.alert.notEnough": "Not enough currency.",
    "shop.alert.alreadyOwned": "Already owned.",
    "shop.alert.loginNeeded": "Please log in.",
    "shop.alert.buyLoginNeeded": "You need to log in to buy.",
    "shop.buying": "Buying...",
    "shop.purchased": "Purchased “{name}”!",
    "shop.buyFailed": "Purchase failed ({msg})",

    // --- Rankings ---
    "rank.title": "📊 Rankings",
    "rank.cat.winRate": "Win rate",
    "rank.cat.wins": "Wins",
    "rank.cat.matches": "Matches",
    "rank.value.winRate": "{v}%",
    "rank.value.wins": "{v} W",
    "rank.value.matches": "{v} G",
    "rank.empty": "No eligible players yet.",
    "rank.rules.title": "Ranking rules",
    "rank.rules.b1": "・The Win-Rate Top 3 ranking only includes players whose match count exceeds 50% of the average match count among players who have actually played — so players with very few matches can't reach the top after just a few games.",
    "rank.rules.border": "Current average match count among active players: {average} → eligibility threshold: more than {border} matches",
    "rank.rules.b2": "・Tie-break order: ① win rate → ② wins → ③ matches; if all are equal, players share the same rank.",
    "rank.rulesBtnTip": "View ranking rules",
    "rank.loading": "Loading…",
    "rank.loadFail": "Failed to load rankings. Please check your connection.",
    "rank.iconTip": "Open rankings",
    "rank.iconCaption": "Rankings",
    "rank.iconDetail": "Check the win-rate, wins, and matches rankings.",

    "phase.titleSuffix": "{label} Phase",

    // --- In-game notifications and effects (phase 6) ---
    "game.you": "you",
    "game.seat": "Player {seat}",
    // --- Phase 7: in-game modals and prompts ---
    "game.effectOf": "“{card}” effect",
    "game.thisCard": "this card",
    "game.ritual.toPlayer": "to {name}",
    "game.ritual.fromXtoY": "{actor} from {target}",
    "game.ritual.fromPlayer": "from {name}",
    "game.pick.fromHand": "Choose one card from {name}’s hand",
    "game.pick.fromHandFaceDown": "Choose one card from {name}’s face-down hand",
    "game.pick.randomFromHand": "Pick one at random from {name}’s face-down hand",
    "game.ritual.receivedFrom": "Received from {name}",
    "game.ritual.gaveTo": "Given to {name}",
    "game.ritual.aboutToSteal": "You will now choose {n} card(s) to take from {name}’s hand.",
    "game.ritual.pickN": "Choose {n} card(s) to take ({sel}/{n})",
    "game.ritual.confirmN": "✅ Confirm ({sel}/{n})",
    "game.ritual.pickStealFaceDown": "Choose a card to take from {name}’s face-down hand ({i}/{n})",
    "game.ritual.attackerTakes": "{name} is taking {n} card(s) from your hand…",
    "game.ritual.tapToFlip": "Tap to flip the {n} card(s) taken…",
    "game.ritual.pickOneFaceDown": "Choose 1 card to take from {name}’s face-down hand",
    "game.ritual.pickOneFor": "{attacker}: choose 1 card to take from {defender}’s face-down hand",
    "game.choice.chose": "{name} chose “{label}”.",
    "game.choice.made": "{name} made a choice.",
    "game.declare.byPlayer": "{name} declares",
    "game.declare.exact": "Declare exactly {n} color(s)",
    "game.declare.atLeast": "Declare at least {n} color(s)",
    "game.slum.discardTo3": "Discard until you have 3 cards ({n} to go)",
    "game.waitingChoice": "Waiting for {name} to choose…",
    "game.confirm.lockCard": "Lock {card}?",
    "game.confirm.useCard": "Use {card}?",
    "game.anytime.haveNamed": "{name}: you have a card you can use anytime",
    "game.cpuStepHint": "▶ Click to continue",
    "game.handEffect.notUsable": "“{card}” has no Hand Effect you can use.",
    "game.contactResult.tookFrom": "You took “{card}” from {name}!",
    "game.contactResult.nothingToTake": "{name} had no cards, so nothing was taken.",
    "game.contactResult.lostTo": "{name} took “{card}” from you…",
    "game.contactResult.nothingLost": "{name} made contact, but you had no cards to lose.",
    "game.brand.locked": "{name} locked a card in the {brand} color slot. {brand} makes them discard 2 cards.",
    "game.brand.pickDiscard": "{brand}: choose a card to discard",
    "game.brand.pickCell": "{brand}: choose a square to place it face-down",
    "game.brand.placed": "{brand} was placed face-down on the board{where}.",
    "game.brand.placedAt": " at {coord}",
    "game.brand.drawAskN": "🖋 {brand}: you didn’t lock, so you may draw for brand {i} of {total}. Draw? (optional)",
    "game.brand.drawAsk1": "🖋 {brand}: you didn’t lock, so you may draw 1 card. Draw? (optional)",
    "game.brand.drewBecauseNoLock": "{name} didn’t lock, so {brand} let them draw 1 card.",
    "game.myDeck.drewAnnounce": "{name} drew 1 card from their deck.",
    "game.counterLock.cancelled": "{defender}’s Counter Lock cancelled {attacker}’s contact.",
    "game.pileTooltip": "{label} — {n}",
    "game.pileTooltipDiscard": "{label} — {n} (double-tap for the list)",
    "game.handTooltip": "{name} — {n} in hand",
    "game.discardBar": "Discard {n}",
    "game.stack.title": "Stacked cards ({n}, bottom to top)",
    "game.discardList.titleN": "Discard pile ({n}, top first)",
    "game.gomennasai.blocks": "{name} uses Sorry! to take one locked card from {attacker} and stop the final lock!",
    "game.gomennasai.tookFrom": "{name} took a card from {attacker}’s Lock Area",
    "game.autoToggle.title": "⚙️ {name} proposes turning auto-processing {state}!",
    "game.autoToggle.needYou": "Your approval ({name}) is required",
    "game.autoToggle.waiting": "Waiting for {name} to approve…",
    "game.autoToggle.approve": "✅ Approve",
    "game.autoToggle.reject": "🚫 Reject",
    "game.log.arrival": "Gained the Arrival Effect of “{card}”{where}",
    "game.log.coordSuffix": " ({coord})",
    "game.log.handEffect": "Used the Hand Effect of “{card}”",
    "game.log.lockedCard": "Locked “{card}”",
    "game.log.declared": "Declared colors: {colors}",
    "game.log.brandDrawN": "Drew 1 card from the Black Brand of Temptation (#{i})",
    "game.log.placedNamed": "Placed “{card}”{fd}{where}",
    "game.log.placedCard": "Placed a card{fd}{where}",
    "game.log.turnOf": "{name}’s turn",
    "game.turnRound": "Turn {turn} / Round {round}",
    "game.unlinked": "Not linked",
    "game.shop.buyFor": "🔒 Buy for {cost}",
    "game.self.meSuffix": "{name} (you)",
    "game.self.handCount": "Hand: {n}",
    "game.pile.deck": "Deck",
    "game.pile.eternal": "Eternal cards",
    "game.pile.first": "First cards",
    "game.pile.discard": "Discard",
    "game.btn.publicDraw": "🎴 Open draw",
    "game.btn.declare": "📣 Declare",
    "game.btn.discard": "🗑 Discard",
    "game.cpuOperating": " 🤖 CPU is playing",
    "game.ritual.shuffling": "Shuffling…",
    "game.ritual.opponentPicking": "Your opponent is choosing a card from your hand…",
    "game.ritual.stolenTheseCards": "These cards were taken!",
    "game.ritual.stolenThisCard": "This card was taken!",
    "game.ritual.tookIt": "Taken!",
    "game.label.took": "Taken",
    "game.label.wasTaken": "Lost",
    "game.label.received": "Received",
    "game.label.handedOver": "Given",
    "game.label.stepped": "Stepped on",
    "game.label.collected": "Collected",
    "game.label.madeDiscard": "Made them discard",
    "game.label.forcedDiscard": "Forced to discard",
    "game.label.gambleReveal": "Gamble reveal",
    "game.label.reveal": "Reveal",
    "game.ritual.gateSuccess": "🚩 Gate invasion successful!",
    "game.ritual.pickStealBtn": "Choose cards to take",
    "game.ritual.onlyOneCard": "This is your only card. Sleight of Hand always swaps one for one, so give this card back to your opponent",
    "game.ritual.giveCard": "Choose a card from your hand to give",
    "game.ritual.stealFailed": "A connection error stopped the steal, so the swap was cancelled. Please try again.",
    "game.pick.emptyCell": "Choose an empty square",
    "game.pick.moveTo": "Choose a square to move to",
    "game.pick.cellWithCardToHand": "Choose the square with the card to add to your hand",
    "game.pick.openCell1": "Choose a square with a card to reveal (1/2)",
    "game.pick.openCell2": "Choose a square with a card to reveal (2/2)",
    "game.pick.placeFromHand": "Choose a card from your hand to place there",
    "game.pick.cannotPickCell": "You can't choose that square.",
    "game.pick.thisCard": "Choose this card?",
    "game.pick.lockSlotCard": "Cards in this slot (choose the one to use)",
    "game.pick.handPhaseCard": "Choose a card to use in the Hand phase",
    "game.pick.stackedCard": "Choose a card to use (bottom to top)",
    "game.pick.noMore": "Stop choosing",
    "game.pick.lockTarget": "Choose a card from your hand to lock",
    "game.pick.lockSlot": "Choose where to lock it",
    "game.pick.stealLock": "Choose a locked card to take",
    "game.pick.discardPurple": "Choose a purple card from your hand to discard",
    "game.place.where": "Where do you want to place from?",
    "game.place.fromDeckBtn": "🂠 From the deck",
    "game.place.fromHandBtn": "🖐 From your hand",
    "game.place.fromDeck": "From the deck",
    "game.place.fromHand": "From your hand",
    "game.place.deckFaceDown": "Place one card from the deck face-down",
    "game.place.handFaceDown": "Place one card from your hand face-down",
    "game.place.noHandSoDeck": "No cards in hand, so placing from the deck",
    "game.party.move": "Move 1 square; you do not gain the Arrival Effect there.",
    "game.party.pickup": "Add any one card on the board to your hand.",
    "game.party.openTwo": "Reveal any two cards on the board.",
    "game.declare.viewBoard": "View the board",
    "game.declare.viewingBoard": "Viewing the board… click to go back to the choices",
    "game.declare.submit": "Declare",
    "game.color.red": "Red",
    "game.color.orange": "Orange",
    "game.color.yellow": "Yellow",
    "game.color.green": "Green",
    "game.color.blue": "Blue",
    "game.color.pink": "Pink",
    "game.color.purple": "Purple",
    "game.fizzle.toHand": "Nothing happened, so this card goes to your hand.",
    "game.fizzle.nothing": "Nothing happened.",
    "game.handEffect.onlyHandPhase": "You can use this card's effect during your own Hand phase.",
    "game.handEffect.noCost": "You have no same-color card in hand to discard as the cost.",
    "game.handEffect.cantUseNow": "You can't use this card's effect right now.",
    "game.handEffect.dropToUse": "Drop that card onto the board to trigger its Hand Effect.",
    "game.handEffect.noMoveThisTurn": "Marumego turned up orange, so you can't move this turn (contact is still allowed).",
    "game.anytime.resumeBtn": "🔔 Resume interrupt prompts",
    "game.anytime.resumeTip": "Shows the “anytime” interrupt prompt again after you chose to hide it.",
    "game.anytime.have": "You have a card you can use anytime",
    "game.anytime.use": "Use",
    "game.anytime.never": "Don't show this again",
    "game.confirm.yes": "✅ Yes",
    "game.confirm.no": "🚫 No",
    "game.confirm.yesPlain": "Yes",
    "game.confirm.noPlain": "No",
    "game.confirm.never": "Don't show this again",
    "game.confirm.cancel": "Cancel",
    "game.confirm.close": "Close",
    "game.contactResult.title": "🤝 Contact result",
    "game.contact.reallyQ": "Really make contact?",
    "game.contact.requestBtn": "🤝 Request contact",
    "game.contact.doBtn": "🤝 Contact",
    "game.counterLock.askLock": "🛡️ Counter Lock: lock one card from your hand into your Lock Area? (optional)",
    "game.counterLock.lock": "Lock it",
    "game.counterLock.dont": "No thanks",
    "game.brand.name": "Black Brand of Temptation",
    "game.brand.draw": "Draw",
    "game.brand.dont": "No thanks",
    "game.brand.drewOne": "Drew 1 card from the Black Brand of Temptation",
    "game.myDeck.drewOne": "Drew 1 card from your deck",
    "game.gomennasai.blockBtn": "Stop their final lock",
    "game.gomennasai.reason": "Taken from a Lock Area with Sorry!",
    "game.gomennasai.costFailed": "Couldn't discard the color cost (possible connection error). Press “Use Sorry!” again.",
    "game.gateAuto.title": "Gate Invasion Bonus",
    "game.gateAuto.body": "The Gate Invasion Bonus conditions are met. Process it automatically?",
    "game.gateAuto.manual": "No (I'll do it myself)",
    "game.gateAuto.auto": "Process automatically",
    "game.gateAuto.happened": "A gate invasion happened",
    "game.gate.collectedOwn": "Collected from your own gate",
    "game.open.yes": "👁 Reveal",
    "game.open.no": "🚫 Don't reveal",
    "game.menu.cardNote": "View card notes",
    "game.menu.stackedCards": "View the stacked cards",
    "game.menu.cardBack": "Change card back design",
    "game.menu.deckList": "View the card list",
    "game.menu.discardList": "View the discard pile",
    "game.menu.pieceSkin": "Change piece skin",
    "game.menu.hideLockBar": "Hide the Lock Area bar",
    "game.menu.hideLockBarDone": "Lock Area bar hidden",
    "game.menu.hideLockBarHint1": "Tick “Show the Lock Area bar” under ⚙ Options → Settings",
    "game.menu.hideLockBarHint2": "to bring it back at any time.",
    "game.menu.playmat": "Change playmat",
    "game.menu.background": "Change background",
    "game.stack.noNote": "(no notes)",
    "game.discardList.title": "Discard pile",
    "game.discardList.empty": "The discard pile is empty.",
    "game.spectate.leave": "Stop spectating",
    "game.spectate.all": "👀 Spectating (everything visible)",
    "game.spectate.public": "👀 Spectating (public info only)",
    "game.log.title": "📜 Action log",
    "game.log.howToTitle": "📜 How to read the action log",
    "game.log.howToBtn": "How to read it",
    "game.log.h1": "Newest actions appear at the top. Entries are grouped by round (R) and turn (T), and the player whose turn it is is shown with their avatar and color.",
    "game.log.h2": "What is recorded: Arrival Effects, Hand Effects, color declarations, gate invasions, and so on.",
    "game.log.h3": "Square coordinates (e.g. C3) are absolute board coordinates: columns A–G from the left, rows 1–7 from the top. C3 is the 3rd column, 3rd row. (The board rotates per player, but the coordinates stay the same for everyone.)",
    "game.log.h4": "Repeated identical entries are merged into one line.",
    "game.log.empty": "(nothing recorded yet)",
    "game.log.toggleTip": "Show/hide the action log (handy after stepping away)",
    "game.log.caption": "Log",
    "game.log.bullet": " · ",
    "game.log.lockArea": " (Lock Area)",
    "game.log.faceDown": "face-down ",
    "game.online.title": "Online play",
    "game.online.help1": "Sign in to create a room and play with friends anywhere (the icon shows three states: signed out, signed in, in a room).",
    "game.online.help2": "While you're in a room, its name appears under the icon. Click it for room details (players, leaving, and so on).",
    "game.online.inRoomTip": "You're in an online match. Click for room details",
    "game.online.signedInTip": "You're signed in. Click to see the room list",
    "game.online.signedIn": "Signed in",
    "game.online.signInTip": "Sign in to play online",
    "game.online.caption": "Online",
    "game.self.emote": "Click to pick an emote",
    "game.self.pieceSkin": "Click to change your piece skin",
    "game.self.cardBack": "Click to change the card back (only on your own screen)",
    "game.self.playmat": "Click to change the playmat",
    "game.self.background": "Click to change the background",
    "game.self.pet": "Click to change your pet",
    "game.self.name": "Click to change your name",
    "game.self.titleTip": "Change it from “Titles” on My Page",
    "game.self.handCountLabel": "Cards in hand",
    "game.self.me": "you",
    "game.bug.tip": "Report a bug (sends your comment and logs)",
    "game.bug.caption": "Report a bug",
    "game.profile.title": "🎉 Check your profile",
    "game.profile.body": "Pick a nickname and an avatar (you can change them later).",
    "game.profile.nickname": "Nickname",
    "game.profile.nicknamePh": "Enter a nickname",
    "game.profile.start": "Start with these",
    "game.profile.pickAvatar": "Choose an avatar",
    "game.profile.useGoogle": "Use my Google profile picture",
    "game.profile.useUpload": "Use an uploaded image",
    "game.profile.protagonist": "The youth who lost his memory (color follows your piece)",
    "game.afk.substituting": "🤖 A CPU is playing for you (you were away).",
    "game.afk.resume": "Take over again",
    "game.afk.opponentLost": "Your opponent forfeited by being away, so you win.",
    "game.afk.youLost": "You forfeited by running out of time repeatedly.",
    "game.afk.alreadyWon": "This match is already over (you won).",
    "game.afk.alreadyLost": "This match is already over: you forfeited by running out of time.",
    "game.room.closed": "This match has ended (the room was closed). Returning home.",
    "game.loginBonus.title": "🎁 Daily bonus",
    "game.loginBonus.body": "Thanks for playing today! (once per day)",
    "game.loginBonus.claim": "Claim",
    "game.myDeck": "My Deck",
    "game.pickup.fromDiscard": "Taken from the discard pile",
    "game.pickup.fromDeck": "Drawn from the deck",
    "game.turnOf": "{name}’s turn",
    "game.victory.title": "{name} wins!",
    "game.victory.sub": "All seven colors are locked in their Lock Area",
    "game.toast.hiddenGain": "{name} added {n} hidden card(s) to hand",
    "game.toast.gained": "{name} gained",
    "game.toast.hiddenNote": "+{n} hidden card(s)",
    "game.toast.gateTitle": "Gate Invasion Bonus!",
    "game.toast.gateText": "{attacker} invaded {defender}’s gate!",
    "game.toast.draws": "{name} draws {n} card(s)",
    "game.toast.locked": "{name} locked a card",
    "game.toast.discarded": "{name} discarded",
    "game.chip.gainedN": "{name} gained {n} card(s)",
    "game.chip.gained": "{name} gained a card",
    "game.chip.gate": "{name} invaded a gate",
    "game.chip.draw": "{name} drew {n} card(s)",
    "game.chip.lock": "{name} locked ({card})",
    "game.chip.discard": "{name} discarded ({card})",
    "game.chip.reason": " ({reason})",
    "game.chip.reasonSlash": " / {reason}",
    "game.contact.title": "🤝 Contact request",
    "game.contact.bodyCounter": "{attacker} is requesting contact with you ({defender}). You hold a Counter Lock — use it? (Using it cancels this contact.)",
    "game.contact.bodySelf": "{attacker} is requesting contact with you ({defender}). If you approve, you give one random card from your hand and are forced back to your own gate.",
    "game.contact.bodyWait": "{attacker} is requesting contact with {defender}… waiting for their answer.",
    "game.contact.useCounter": "🛡️ Use Counter Lock",
    "game.contact.declineCounter": "Don’t use it (approve)",
    "game.contact.approve": "✅ Approve",
    "game.contact.reject": "🚫 Reject",
    "game.finalLock.gomennasaiTitle": "🍬 Sorry!",
    "game.finalLock.gomennasaiPick": "Choose a card to take from their Lock Area",
    "game.finalLock.title": "🔒 {name} is attempting the final lock!",
    "game.finalLock.needYou": "Your approval ({name}) is required",
    "game.finalLock.waiting": "Waiting for {name} to approve…",
    "game.finalLock.approve": "✅ Approve",
    "game.finalLock.useGomennasai": "🍬 Use Sorry!",
    "game.gate.title": "Gate Invasion Bonus",
    "game.gate.skip": "Skip",
    "game.gate.hiddenNote": "+{n} hidden card(s)",
    "game.gate.step.invade": "{attacker} invaded {defender}’s gate!",
    "game.gate.step.stealIntro": "{attacker} pulled off the gate invasion!\nTaking {n} random card(s) from {defender}’s hand.",
    "game.gate.step.stealDone": "{attacker} took {n} card(s) from {defender}’s hand.",
    "game.gate.step.stealNone": "{attacker} pulled off the gate invasion!\n{defender} has fewer than half a hand, so there is nothing to take.",
    "game.gate.step.eternal": "{attacker} gained the Eternal card “{card}”!\nIt is locked into their own Lock Area.",
    "game.gate.step.eternalPushed": "The card that was in that lock slot was pushed out and added to {attacker}’s hand.",
    "game.gate.step.eternalEmpty": "{attacker} would have gained an Eternal card, but none are left outside the board.",
    "game.gate.step.returnHomeCards": "{attacker} collects every card on their own gate and returns there.",
    "game.gate.step.returnHome": "{attacker} returns to their own gate.",
    "game.gate.reason.steal": "Gate Invasion Bonus (cards taken from hand)",
    "game.gate.reason.bumped": "Gate Invasion Bonus (pushed out of a lock slot)",
    "game.gate.reason.collected": "Gate Invasion Bonus (collected from your own gate)",
  },
};

export function t(key, params) {
  const lang = getLang();
  let s = (UI[lang] && UI[lang][key]) ?? UI.ja[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}
