// アプリのUI文言（メニュー・ボタン等）の多言語化。カードのテキスト(card-text)とは別レイヤー。
// t(key, params) が現在の言語(getLang)の文字列を返す。未定義キーは ja にフォールバックし、
// ja にも無ければキー文字列をそのまま返す（開発中の抜けが画面に見えるように）。
// params は {name} 形式のプレースホルダを置換する（例: t("home.comingSoon", {label:"X"})）。
//
// UI英語化は段階的に進める。まずは最も目に付く画面（ホーム）から。翻訳済みのキーだけを
// ここに足していき、各ファイルはハードコード文字列を t("...") に置き換える。
import { getLang } from "./i18n.js";

const UI = {
  ja: {
    // --- ホーム画面（home-screen.js） ---
    "home.subtitle": "ホーム",
    "home.tile.tutorial": "物語チュートリアル",
    "home.tile.match": "CPUマッチ＆フレンドリーマッチ",
    "home.tile.ranked": "フリーマッチ（ランク戦）",
    "home.tile.shop": "ショップ",
    "home.tile.ranking": "ランキング",
    "home.tile.mypage": "マイページ／マイデッキ編集",
    "home.tile.codex": "図鑑／ルールブック",
    "home.tile.news": "お知らせ／更新情報",
    "home.comingSoon": "「{label}」は近日公開予定です。お楽しみに！",
    "home.comingSoonBadge": "近日公開",
    "home.newBadge": "NEW",
    "home.matchChoice.title": "対戦モードを選択",
    "home.matchChoice.friendly": "フレンドリーマッチ",
    "home.matchChoice.friendlyDesc": "オンラインで対戦（部屋を作る／参加する）",
    "home.matchChoice.cpu": "CPU戦（1人用）",
    "home.matchChoice.cpuDesc": "この端末でCPUと対戦（ログイン不要）",
    "home.matchChoice.difficultyLabel": "🤖 CPUの強さ（CPU戦のみ）",
    "home.matchChoice.difficultyHint": "新人＝ランダム／中級・上級＝賢い思考／最強＝伏せカードののぞき見あり",
    "home.matchChoice.countLabel": "👥 人数（CPU戦のみ）",
    "home.matchChoice.countHint": "あなた＋CPU（3人・4人はCPUが2体・3体に増えます）",
    "home.rankLabel": "あなたのランク",
    "home.rankAboutTitle": "ランク戦について",
    "home.waitingBadge": "🟢 {count}人が対戦募集中！",
    "common.back": "← 戻る",
    // --- CPUの強さ・人数（home / options 共有） ---
    "cpu.diff.rookie": "新人",
    "cpu.diff.intermediate": "中級",
    "cpu.diff.advanced": "上級",
    "cpu.diff.master": "最強",
    "cpu.count.2": "2人",
    "cpu.count.3": "3人",
    "cpu.count.4": "4人",
    // --- オプション（options-menu.js） ---
    "opt.title": "オプション",
    "opt.basicSettings": "基本設定",
    "opt.detailSettings": "詳細設定",
    "opt.detailSettingsHint": "画面の見え方・動作の軽さ・CPU戦・通知・ショートカットなど",
    "opt.backToBasic": "← 基本設定へ戻る",
    "opt.reset": "戻す",
    "opt.soundVolume": "効果音の音量",
    "opt.bgmVolume": "BGMの音量",
    "opt.langNote": "現在はカードのテキストのみ翻訳されます（メニュー等は順次英語化中）。",
    "opt.cardPreviewSize": "カードを拡大表示する大きさ",
    "opt.cardPreviewSide": "カード拡大を出す向き",
    "opt.cpuSpeed": "CPUの速さ",
    "opt.cpuStrength": "CPUの強さ",
    "opt.resetAccount": "アカウント設定を初期化する",
    "opt.resetAccountDesc": "名前・アバター・駒スキン・プレイマット・カード裏面・背景画像を既定に戻します。",
    "opt.resetAccountConfirm": "本当に初期化しますか？（もう一度クリック）",
    "opt.resetAccountBusy": "初期化中…",
    "opt.resetAccountFailed": "初期化に失敗しました",
    "opt.statsLink": "🏆 戦績管理システムのプレイヤーと連携",
    "opt.statsLinkSelect": "選択する",
    "opt.statsLinkDone": "✅ 連携済みです",
    "opt.statsLinkGoogleOnly": "Googleアカウントでログインしていないと連携できません。",
    "opt.statsLinkReloginGoogle": "Googleアカウントでログインしなおす",
    "opt.pressKey": "キーを押してください…",
    // 続き299「基本設定のUIを整備（ライトユーザーに優しくない）」で、セクション名を
    // 「機能の種類」から「困りごと」へ、項目名を「何が起きるか」の言葉へ書き換えた。
    // 旧 volume/display/autoTimer/lockArea/reduceAnim はもう使っていないが、他所からの
    // 参照が残っていても壊れないようキー自体は残す。
    "opt.sec.group.volume": "音量",
    "opt.sec.group.display": "表示・演出",
    "opt.sec.group.autoTimer": "自動処理・タイマー",
    "opt.sec.group.common": "よく使う設定",
    "opt.sec.group.heavy": "動きが重い・カクつくとき",
    "opt.sec.group.look": "画面の見え方",
    "opt.sec.group.auto": "カードの効果を自動で処理する",
    "opt.sec.group.advanced": "テスト用・上級者向け",
    "opt.chk.boardIllustOnly": "盤面のカードを絵だけで表示する（遠くからでも見分けやすい／手札と拡大表示はそのまま）",
    "opt.chk.fixedHand": "自分の手札をいつも画面の下に置く（盤面を拡大しても見切れない）",
    "opt.chk.flatten2d": "盤面を平らな2D表示にする（タブレットで画面がちらつく時に）",
    "opt.chk.fullscreen": "全画面で遊ぶ（ブラウザのタブやURL欄を隠す）",
    "opt.chk.opponentBaseTimer": "相手の持ち時間も表示する",
    "opt.chk.actionConfirm": "ロックやカードを使う前に確認する（うっかり操作を防ぐ）",
    "opt.sec.lockArea": "ロックエリア関連",
    "opt.chk.lockAreaBar": "ロックエリアのバーを表示する",
    "opt.chk.lockColor": "ロックエリアに色を付ける",
    "opt.sec.modalDuration": "お知らせの表示時間",
    "opt.sec.reduceAnim": "アニメーションを減らす（動作が重い時に）",
    "opt.chk.disableFlight": "駒やカードが飛ぶ動きをやめる",
    "opt.chk.disableArrival": "到達・ロックの光る演出をやめる",
    "opt.chk.disableGlow": "ずっと光り続ける演出をやめる（手番の光・砂時計のロープなど）",
    "opt.chk.cpuAutoAdvance": "CPUの結果通知を自動で進める（OFFにするとクリックするまで表示）",
    "opt.rankedAutoFixed": "ランク戦では自動処理は常にONで固定されます。",
    "opt.autoProcessing": "カード効果を自動処理する",
    "opt.emergencyEndTurn": "🚨 緊急ターン終了",
    "opt.sec.cpuBattle": "CPU戦（1人用）",
    "opt.sec.rankedNotify": "ランク戦の通知",
    "opt.sec.shortcuts": "ショートカットキー（プレイヤー用ボタン）",
    "opt.shortcutRecommended": "⭐ おすすめ",
    "opt.adminMode": "⚙ 管理者モード",
    "opt.notify.enable": "対戦相手が現れたら通知する",
    "opt.notify.timeLabel": "通知してもいい時間帯",
    "opt.notify.hint": "開始と終了を同じ時刻にすると終日OKです。開始＞終了なら夜をまたぎます（例 22時〜6時）。",
    // --- ゲーム中のボタン（main.js） ---
    "btn.endTurn.caption": "ターン終了",
    "btn.endTurn.detail1": "自分のターンを終え、次のプレイヤーへ手番を渡します。",
    "btn.endTurn.detail2": "相手のゲートに自分の駒が乗っている場合、ターン終了時に「相手ゲート侵攻ボーナス」が自動的に処理されます。",
    "btn.endTurn.otherTurn": "今は{name}のターン中です",
    "btn.endTurn.otherPriority": "今は{name}が優先権を持っています",
    "btn.endTurn.tooltipSelf": "自分のターンを終了します",
    "btn.endTurn.tooltipLocal": "{name}のターンを終了します",
    "btn.boardZoom.caption": "盤面拡大",
    "btn.boardZoom.label0": "盤面拡大",
    "btn.boardZoom.label1": "もっと拡大",
    "btn.boardZoom.label2": "元に戻す",
    "btn.boardZoom.returnToView": "元の画角に戻る",
    "btn.boardZoom.detail1": "盤面全体をズームして見やすくします。まだ画角を登録していない間は、押すたびに「拡大」→「もっと拡大」→「元に戻す」の3段階を切り替えます。",
    "btn.boardZoom.detail2": "マウスホイールでの自由なズームや中クリックドラッグでの視点移動を一度でも使うと、代わりに「元の画角に戻る」ボタンに変わります。その間だけ現れる点滅した「拡大率登録」ボタンを押すと、今の画角を登録できます。登録後は、通常表示からこのボタンを押すと登録した画角へ一気に切り替わります。",
    "btn.handShuffle.caption": "手札シャッフル",
    "btn.handShuffle.tooltip": "自分の手札の並び順をシャッフルします（カードの中身は変わりません）",
    "btn.handShuffle.detail1": "自分の手札の並び順だけをシャッフルします。カードの中身（持っている手札）自体は変わりません。",
    "btn.handShuffle.detail2": "相手に手の内を推測されにくくするための、見た目上の演出です。",
    "btn.draw.caption": "1枚ドロー",
    "btn.draw.tooltip": "山札から1枚引いて手札に加えます",
    "btn.draw.detail1": "山札の一番上のカードを1枚引いて、自分の手札に加えます。",
    "btn.draw.detail2": "山札が無くなった場合は、捨て場を裏向きのまま新しい山札とします（シャッフルはしません）。",
    "btn.publicDraw.caption": "公開ドロー",
    "btn.publicDraw.tooltip": "山札から1枚、表向きで公開ドローします",
    "btn.publicDraw.detail1": "山札の一番上のカードを1枚引き、表向きのまま手札の近くに公開して並べます（扇状の手札には直接入りません）。",
    "btn.publicDraw.detail2": "「手札シャッフル」または「ターンを終了する」を押すと、公開ドローしたカードがまとめて通常の手札へ合流します。",
    // --- フェイズ案内板（phase-guide.js。tutorial.js/help.jsとも共有） ---
    "phase.titleSuffix": "{label}フェイズ",
    "phase.lock.label": "ロック",
    "phase.lock.short": "手札を1枚だけロックできます（任意）",
    "phase.lock.d1": "あなたの手札を1枚だけロックしてもよい（ロックしなくてもよい）。",
    "phase.lock.d2": "ロックしたカードは原則、手札ではなくなり手札効果を使用できない（例外: ファーストカードとエターナルカードの手札効果は特別に使用できる）。",
    "phase.hand.label": "ハンド",
    "phase.hand.short": "手札を何枚でも使えます（任意）",
    "phase.hand.d1": "あなたの手札を何枚でも使ってもよい（使わなくてもよい）。手札効果はそのカード自身を捨てることで得ることができる。",
    "phase.hand.d2": "使用する時以外、手札は原則、相手に見せないようにプレイする。手札枚数に上限はない。",
    "phase.move.label": "ムーブ",
    "phase.move.short": "「移動」か「接触」のどちらかを必ず行います",
    "phase.move.d1": "ムーブフェイズでは、次のどちらか一方を必ず行います。",
    "phase.move.d2": "🚶 移動：自分の隣（前後左右の4マス）の、カードだけが置かれたマスへ駒を置きます。",
    "phase.move.d3": "　カードが裏向きならオープンします。表向きなら「到達」効果が発動し、そのカードは原則そのまま手札に加わります。",
    "phase.move.d4": "　相手の駒がいるマスへは移動できません。",
    "phase.move.d5": "🤝 接触：隣にいる相手の駒を選び、その相手の手札から無作為に1枚もらいます。",
    "phase.move.d6": "　接触された相手は自分のゲートへ強制移動します（接触した自分自身は動きません）。",
    "phase.move.d7": "📥 隣に「カード」も「相手の駒」も無い場合：隣の任意の1マスへ山札から1枚表向きに置いてターンを終了します。",
    "phase.autoSkip.caption": "自動送り",
    "phase.autoSkip.on": "ON",
    "phase.autoSkip.off": "OFF",
    "phase.autoSkip.titleOn": "フェイズ自動送り: ON（することが無いフェイズは自動でスキップします）",
    "phase.autoSkip.titleOff": "フェイズ自動送り: OFF（自分でスキップを押すまでフェイズを送りません。ロックできる手札が無いこと等を相手に悟られません）",

    // --- オープニング/ログイン画面（opening-screen.js） ---
    "opening.loginToggle": "ログイン",
    "opening.testMode": "テストモード",
    "opening.testMode.tip": "1画面で複数人分を動かせる検証用の盤面へ直接進みます（開発・動作確認用）",
    "opening.adminPanel": "🔧 管理者パネル",
    "opening.adminPanel.tip": "管理者モード（設定・利用状況・ユーザー一覧など）を開きます",
    "opening.versionTip": "アプリのバージョン（デプロイ日時）",
    "opening.clickToClose": "クリックで閉じる",
    "opening.clickToSkip": "クリックでスキップ",
    "opening.localPlay": "ローカルでプレイ（ログイン不要）",
    "opening.onlineLoadFail": "オンライン機能を読み込めませんでした。ローカルでプレイできます。",
    "opening.loggedInTitle": "🌐 ログイン中（{name}）",
    "opening.continueOnline": "オンラインで続ける",
    "opening.logout": "ログアウト",
    "opening.testModeHint": "🧪 テストモード：ログイン完了後、「オンラインで続ける」を経由せず直接検証用の盤面へ進みます。通常のオンライン対戦をしたい場合は右上の✕で引き返してください。",
    "opening.googleLogin": "Googleでログイン",
    "opening.error": "エラー: {msg}",
    "opening.googleInfo.title": "アカウントでログインするメリット",
    "opening.googleInfo.b1": "名前・アバター・駒スキンなどの設定が、別の端末・別のブラウザからログインしても引き継がれます。",
    "opening.googleInfo.b2": "戦績管理システムのプレイヤーとの連携も、アカウントに紐づけて保存されるため、次にログインした時も選び直す必要がありません。",
    "opening.googleInfo.b3": "ゲストログインと違い、ログアウトしたり端末を変えたりしても、同じアカウントとして続けて遊べます。",
    "opening.guestLogin": "ゲストでログイン",
    "opening.loggingIn": "ログイン中...",
    "opening.guestInfo.title": "ゲストログインについて",
    "opening.guestInfo.b1": "メールアドレスの登録・確認は不要で、今すぐそのままオンライン対戦に参加できます。",
    "opening.guestInfo.b2": "ただし一度ログアウトしたり、別の端末・別のブラウザからアクセスすると同じアカウントには戻れません（ゲストアカウントを後から引き継ぐ手段は現在ありません）。",
    "opening.guestInfo.b3": "何度も遊ぶ予定がある場合や、名前・アバター・駒スキン等の設定を長く使い続けたい場合は、上のGoogleでログインすることをおすすめします。",
    "opening.guestConfirm.title": "⚠️ ゲストでログインする前に",
    "opening.guestConfirm.body": "ゲストログインでは、ランキングへの参加や、名前・アバター・駒スキン等の設定の記憶といった恩恵を受けられません。また、一度ログアウトしたり別の端末・別のブラウザからアクセスすると、このアカウントには二度と戻れません。",
    "opening.guestConfirm.yes": "承知の上でゲストで始める",
    "opening.guestConfirm.no": "やめる",
    "opening.moreLogin.closed": "その他のログイン方法（メール） ▾",
    "opening.moreLogin.open": "その他のログイン方法（メール） ▴",
    "opening.emailPlaceholder": "メールアドレス",
    "opening.sendMagicLink": "マジックリンクを送る",
    "opening.sending": "送信中...",
    "opening.checkEmail": "メールを確認し、届いたリンクを開いてください。",
    // ストーリーテロップ（起動時の導入テロップ、空行は本文の""で表現）
    "opening.story.1": "ここは異世界「ファルベンド」",
    "opening.story.2": "世界は「色」で満ちている",
    "opening.story.3": "この世界には、7つの国があり",
    "opening.story.4": "各国はそれぞれの色を治めている",
    "opening.story.5": "そして、均衡は保たれ平和を築いていた",
    "opening.story.6": "しかし、世界の「色」は突如――",
    "opening.story.7": "消えた",
    "opening.story.8": "各国は、それぞれ国宝を有していた",
    "opening.story.9": "それはその国の「色」を纏った「キューブ」",
    "opening.story.10": "しかし、なぜかその「キューブ」だけは",
    "opening.story.11": "「色」を失わなかった",
    "opening.story.12": "色を失った世界で民は輝きを失い途方にくれていた",
    "opening.story.13": "やがて各国の国王は",
    "opening.story.14": "その「キューブ」の「特殊な力」に気付く",
    "opening.story.15": "そうそれは、「色」を「具現化する力」だった",
    "opening.story.16": "「色」はこの世のあらゆるものと",
    "opening.story.17": "密接に関わっている",
    "opening.story.18": "モノ、記憶、能力、あらゆるものに",
    "opening.story.19": "ある時「キューブ」の力が国王に語りかける",
    "opening.story.20": "-7つの色を集めよ-",
    "opening.story.21": "7つの色を集めたら　一体どうなるのか",
    "opening.story.22": "各国のそれぞれの野望、思惑、理想が交錯する中",
    "opening.story.23": "7色を巡る戦いが",
    "opening.story.24": "今、はじまる",

    // --- ショップ（shop.js / shop-content.js） ---
    "shop.title": "ショップ",
    "shop.cat.pieceSkin": "🎲 駒スキン",
    "shop.cat.cardBack": "🂠 カード裏面",
    "shop.cat.playmat": "🟩 プレイマット",
    "shop.cat.background": "🖼️ 背景画像",
    "shop.cat.pet": "🐾 ペット",
    "shop.cat.avatar": "😀 アバター",
    "shop.cat.mydeck": "🃏 マイデッキ枠",
    "shop.ribbon.free": "無料",
    "shop.ribbon.owned": "所持済み",
    "shop.balance.loginPrompt": "ログインすると通貨を貯められます",
    "shop.balance": "所持通貨: 🪙 {n}",
    "shop.completion": "🏆 コレクション達成率: {percent}%（{owned}/{total}）",
    "shop.petTip": "クリックで動くよ",
    "shop.alert.notEnough": "通貨が足りません。",
    "shop.alert.alreadyOwned": "既に所持しています。",
    "shop.alert.loginNeeded": "ログインしてください。",
    "shop.alert.buyLoginNeeded": "購入にはログインが必要です。",
    "shop.buying": "購入中...",
    "shop.purchased": "「{name}」を購入しました！",
    "shop.buyFailed": "購入に失敗しました（{msg}）",

    // --- ランキング（ranking-page.js） ---
    "rank.title": "📊 ランキング",
    "rank.cat.winRate": "勝率",
    "rank.cat.wins": "勝利数",
    "rank.cat.matches": "対戦数",
    "rank.value.winRate": "{v}%",
    "rank.value.wins": "{v}勝",
    "rank.value.matches": "{v}戦",
    "rank.empty": "まだ対象のプレイヤーがいません。",
    "rank.rules.title": "ランキングのルール",
    "rank.rules.b1": "・勝率TOP3ランキングは、対戦経験が極端に少ないプレイヤーが数試合だけで上位に入ってしまわないように、実際に対戦したことがあるプレイヤーの「平均対戦数」の50%を超える対戦数のプレイヤーのみが対象になります。",
    "rank.rules.border": "現在の実対戦者の平均対戦数: {average}回 → 参加基準(ボーダー): {border}回を超える対戦数",
    "rank.rules.b2": "・同順位の決め方: ①勝率 → ②勝利数 → ③対戦数 の順で比較し、すべて同じ場合は同順位として併記します。",
    "rank.rulesBtnTip": "ランキングのルールを見る",
    "rank.loading": "読み込み中…",
    "rank.loadFail": "ランキングの取得に失敗しました。通信環境を確認してください。",
    "rank.iconTip": "ランキングを開きます",
    "rank.iconCaption": "ランキング",
    "rank.iconDetail": "勝率・勝利数・対戦数のランキングを確認できます。",

    "phase.titleSuffix": "{label}フェイズ",
  },
  en: {
    // --- Home screen ---
    "home.subtitle": "Home",
    "home.tile.tutorial": "Story Tutorial",
    "home.tile.match": "CPU & Friendly Match",
    "home.tile.ranked": "Free Match (Ranked)",
    "home.tile.shop": "Shop",
    "home.tile.ranking": "Rankings",
    "home.tile.mypage": "My Page / Deck Editor",
    "home.tile.codex": "Codex / Rulebook",
    "home.tile.news": "News / Updates",
    "home.comingSoon": "“{label}” is coming soon. Stay tuned!",
    "home.comingSoonBadge": "Coming soon",
    "home.newBadge": "NEW",
    "home.matchChoice.title": "Choose a match mode",
    "home.matchChoice.friendly": "Friendly Match",
    "home.matchChoice.friendlyDesc": "Play online (create or join a room)",
    "home.matchChoice.cpu": "CPU Match (solo)",
    "home.matchChoice.cpuDesc": "Play against the CPU on this device (no login)",
    "home.matchChoice.difficultyLabel": "🤖 CPU strength (CPU match only)",
    "home.matchChoice.difficultyHint": "Rookie = random / Intermediate & Advanced = smart AI / Master = peeks at face-down cards",
    "home.matchChoice.countLabel": "👥 Players (CPU match only)",
    "home.matchChoice.countHint": "You + CPU (3 / 4 players add 2 / 3 CPUs)",
    "home.rankLabel": "Your rank",
    "home.rankAboutTitle": "About ranked play",
    "home.waitingBadge": "🟢 {count} looking for a match!",
    "common.back": "← Back",
    // --- CPU strength / player count (shared home / options) ---
    "cpu.diff.rookie": "Rookie",
    "cpu.diff.intermediate": "Intermediate",
    "cpu.diff.advanced": "Advanced",
    "cpu.diff.master": "Master",
    "cpu.count.2": "2 players",
    "cpu.count.3": "3 players",
    "cpu.count.4": "4 players",
    // --- Options ---
    "opt.title": "Options",
    "opt.basicSettings": "Settings",
    "opt.detailSettings": "More settings",
    "opt.detailSettingsHint": "Look & feel, performance, CPU matches, notifications, shortcuts…",
    "opt.backToBasic": "← Back to settings",
    "opt.reset": "Reset",
    "opt.soundVolume": "Sound effects volume",
    "opt.bgmVolume": "Music volume",
    "opt.langNote": "Currently only card text is translated (menus are being localized).",
    "opt.cardPreviewSize": "Card zoom size",
    "opt.cardPreviewSide": "Card zoom direction",
    "opt.cpuSpeed": "CPU speed",
    "opt.cpuStrength": "CPU strength",
    "opt.resetAccount": "Reset account settings",
    "opt.resetAccountDesc": "Restores name, avatar, piece skin, playmat, card back and background to defaults.",
    "opt.resetAccountConfirm": "Really reset? (click again)",
    "opt.resetAccountBusy": "Resetting…",
    "opt.resetAccountFailed": "Reset failed",
    "opt.statsLink": "🏆 Link a Battle Record player",
    "opt.statsLinkSelect": "Select",
    "opt.statsLinkDone": "✅ Linked",
    "opt.statsLinkGoogleOnly": "You must be signed in with Google to link.",
    "opt.statsLinkReloginGoogle": "Sign in again with Google",
    "opt.pressKey": "Press a key…",
    "opt.sec.group.volume": "Volume",
    "opt.sec.group.display": "Display & Effects",
    "opt.sec.group.autoTimer": "Auto-processing & Timer",
    "opt.sec.group.common": "Everyday settings",
    "opt.sec.group.heavy": "If the game feels slow or stutters",
    "opt.sec.group.look": "How things look",
    "opt.sec.group.auto": "Play card effects automatically",
    "opt.sec.group.advanced": "Testing & advanced",
    "opt.chk.boardIllustOnly": "Show board cards as artwork only (easier to tell apart from afar; hand & zoom unchanged)",
    "opt.chk.fixedHand": "Always keep my hand at the bottom of the screen (stays visible when you zoom the board)",
    "opt.chk.flatten2d": "Show the board flat in 2D (use this if the screen flickers on a tablet)",
    "opt.chk.fullscreen": "Play in fullscreen (hides browser tabs and address bar)",
    "opt.chk.opponentBaseTimer": "Also show opponents' remaining time",
    "opt.chk.actionConfirm": "Ask before locking or using a card (prevents mis-taps)",
    "opt.sec.lockArea": "Lock Area",
    "opt.chk.lockAreaBar": "Show the Lock Area bar",
    "opt.chk.lockColor": "Tint the Lock Area with its colors",
    "opt.sec.modalDuration": "How long notices stay on screen",
    "opt.sec.reduceAnim": "Reduce animations (if performance is poor)",
    "opt.chk.disableFlight": "Stop pieces and cards from flying across the board",
    "opt.chk.disableArrival": "Stop the arrival / lock light effects",
    "opt.chk.disableGlow": "Stop always-on glowing effects (turn glow, hourglass rope, etc.)",
    "opt.chk.cpuAutoAdvance": "Auto-advance CPU result notices (off = shows until clicked)",
    "opt.rankedAutoFixed": "Auto-processing is always ON in ranked matches.",
    "opt.autoProcessing": "Auto-process card effects",
    "opt.emergencyEndTurn": "🚨 Emergency end turn",
    "opt.sec.cpuBattle": "CPU Match (solo)",
    "opt.sec.rankedNotify": "Ranked match notifications",
    "opt.sec.shortcuts": "Shortcut keys (player buttons)",
    "opt.shortcutRecommended": "⭐ Recommended",
    "opt.adminMode": "⚙ Admin mode",
    "opt.notify.enable": "Notify me when an opponent appears",
    "opt.notify.timeLabel": "Allowed notification hours",
    "opt.notify.hint": "Same start and end = all day. Start > end wraps overnight (e.g. 22:00–6:00).",
    // --- In-game buttons ---
    "btn.endTurn.caption": "End turn",
    "btn.endTurn.detail1": "Ends your turn and passes play to the next player.",
    "btn.endTurn.detail2": "If your piece is on an opponent's Gate, the “Gate Invasion Bonus” is processed automatically when your turn ends.",
    "btn.endTurn.otherTurn": "It's {name}'s turn now",
    "btn.endTurn.otherPriority": "{name} has priority now",
    "btn.endTurn.tooltipSelf": "End your turn",
    "btn.endTurn.tooltipLocal": "End {name}'s turn",
    "btn.boardZoom.caption": "Zoom board",
    "btn.boardZoom.label0": "Zoom in",
    "btn.boardZoom.label1": "Zoom more",
    "btn.boardZoom.label2": "Reset",
    "btn.boardZoom.returnToView": "Reset view",
    "btn.boardZoom.detail1": "Zooms the whole board for easier viewing. Until you register a view, each press cycles “Zoom in” → “Zoom more” → “Reset”.",
    "btn.boardZoom.detail2": "Once you use free zoom (mouse wheel) or pan (middle-click drag), this becomes a “Reset view” button. While active, a blinking “Register zoom” button appears — press it to save the current view. After that, pressing this button from the normal view jumps straight to your saved view.",
    "btn.handShuffle.caption": "Shuffle hand",
    "btn.handShuffle.tooltip": "Shuffles the order of your hand (the cards themselves don't change)",
    "btn.handShuffle.detail1": "Shuffles only the order of your hand. The cards you hold do not change.",
    "btn.handShuffle.detail2": "A cosmetic effect to make it harder for opponents to guess your hand.",
    "btn.draw.caption": "Draw 1",
    "btn.draw.tooltip": "Draw 1 card from the deck into your hand",
    "btn.draw.detail1": "Draws the top card of the deck into your hand.",
    "btn.draw.detail2": "If the deck runs out, the discard pile becomes the new deck face-down (no shuffle).",
    "btn.publicDraw.caption": "Open draw",
    "btn.publicDraw.tooltip": "Draw 1 card from the deck face-up (open)",
    "btn.publicDraw.detail1": "Draws the top card of the deck and lays it face-up near your hand (it does not go directly into your fan of cards).",
    "btn.publicDraw.detail2": "Pressing “Shuffle hand” or “End turn” merges the open-drawn cards into your normal hand.",
    // --- Phase guide (shared with tutorial / help) ---
    "phase.titleSuffix": "{label} Phase",
    "phase.lock.label": "Lock",
    "phase.lock.short": "You may lock one card from your hand (optional)",
    "phase.lock.d1": "You may lock exactly one card from your hand (or none).",
    "phase.lock.d2": "A locked card generally leaves your hand and its Hand Effect can't be used (exception: First and Eternal cards' Hand Effects can still be used).",
    "phase.hand.label": "Hand",
    "phase.hand.short": "You may use any number of hand cards (optional)",
    "phase.hand.d1": "You may use any number of cards from your hand (or none). A Hand Effect is gained by discarding that card itself.",
    "phase.hand.d2": "Except when using them, keep your hand hidden from opponents. There is no hand-size limit.",
    "phase.move.label": "Move",
    "phase.move.short": "You must do either “Move” or “Contact”",
    "phase.move.d1": "In the Move phase, you must do exactly one of the following.",
    "phase.move.d2": "🚶 Move: place your piece on an adjacent space (up/down/left/right) that has only a card.",
    "phase.move.d3": "　If the card is face-down it flips; if face-up its Arrival Effect triggers and the card generally goes to your hand.",
    "phase.move.d4": "　You cannot move onto a space occupied by an opponent's piece.",
    "phase.move.d5": "🤝 Contact: choose an adjacent opponent's piece and take one card at random from that opponent's hand.",
    "phase.move.d6": "　The contacted opponent is forced back to their Gate (you yourself don't move).",
    "phase.move.d7": "📥 If there is neither a card nor an opponent's piece adjacent: place one card face-up from the deck on any adjacent space and end your turn.",
    "phase.autoSkip.caption": "Auto-advance",
    "phase.autoSkip.on": "ON",
    "phase.autoSkip.off": "OFF",
    "phase.autoSkip.titleOn": "Phase auto-advance: ON (phases with nothing to do are skipped automatically)",
    "phase.autoSkip.titleOff": "Phase auto-advance: OFF (phases don't advance until you press skip; opponents can't tell you have no lockable cards, etc.)",

    // --- Opening / login screen ---
    "opening.loginToggle": "Log in",
    "opening.testMode": "Test mode",
    "opening.testMode.tip": "Go straight to a sandbox board where you can move all players on one screen (for development/testing).",
    "opening.adminPanel": "🔧 Admin panel",
    "opening.adminPanel.tip": "Open admin mode (settings, usage stats, user list, etc.).",
    "opening.versionTip": "App version (deploy date/time)",
    "opening.clickToClose": "Click to close",
    "opening.clickToSkip": "Click to skip",
    "opening.localPlay": "Play locally (no login)",
    "opening.onlineLoadFail": "Couldn't load online features. You can still play locally.",
    "opening.loggedInTitle": "🌐 Logged in ({name})",
    "opening.continueOnline": "Continue online",
    "opening.logout": "Log out",
    "opening.testModeHint": "🧪 Test mode: after logging in, you'll go straight to the sandbox board without the “Continue online” step. To play a normal online match, close with the ✕ at the top right.",
    "opening.googleLogin": "Log in with Google",
    "opening.error": "Error: {msg}",
    "opening.googleInfo.title": "Benefits of logging in with an account",
    "opening.googleInfo.b1": "Settings like your name, avatar, and piece skin carry over even when you log in from another device or browser.",
    "opening.googleInfo.b2": "Your link to a player in the match-record system is also saved to your account, so you won't have to pick it again next time you log in.",
    "opening.googleInfo.b3": "Unlike guest login, you can keep playing as the same account even after logging out or switching devices.",
    "opening.guestLogin": "Log in as guest",
    "opening.loggingIn": "Logging in...",
    "opening.guestInfo.title": "About guest login",
    "opening.guestInfo.b1": "No email registration or confirmation needed — you can join online matches right away.",
    "opening.guestInfo.b2": "However, once you log out or access from another device or browser, you can't return to the same account (there is currently no way to carry over a guest account later).",
    "opening.guestInfo.b3": "If you plan to play often, or want to keep your name, avatar, piece skin, and other settings long-term, we recommend logging in with Google above.",
    "opening.guestConfirm.title": "⚠️ Before logging in as a guest",
    "opening.guestConfirm.body": "Guest login can't join rankings or remember settings like your name, avatar, or piece skin. Also, once you log out or access from another device or browser, you can never return to this account.",
    "opening.guestConfirm.yes": "Start as guest anyway",
    "opening.guestConfirm.no": "Cancel",
    "opening.moreLogin.closed": "Other login methods (email) ▾",
    "opening.moreLogin.open": "Other login methods (email) ▴",
    "opening.emailPlaceholder": "Email address",
    "opening.sendMagicLink": "Send magic link",
    "opening.sending": "Sending...",
    "opening.checkEmail": "Check your email and open the link we sent.",
    // Opening story crawl (blank lines stay "")
    "opening.story.1": "A world apart: “Farbend.”",
    "opening.story.2": "A world once brimming with color.",
    "opening.story.3": "Seven nations dwell in this world,",
    "opening.story.4": "each ruling over its own color,",
    "opening.story.5": "and in balance they built a lasting peace.",
    "opening.story.6": "But then, all at once, the world's color——",
    "opening.story.7": "vanished.",
    "opening.story.8": "Each nation held a national treasure:",
    "opening.story.9": "a “Cube” clad in that nation's color.",
    "opening.story.10": "Yet for some reason, those Cubes alone",
    "opening.story.11": "never lost their color.",
    "opening.story.12": "In a world drained of color, the people lost their radiance and despaired.",
    "opening.story.13": "In time, the kings of each nation",
    "opening.story.14": "discovered the Cubes' “special power.”",
    "opening.story.15": "It was the power to give color form.",
    "opening.story.16": "Color is intertwined with",
    "opening.story.17": "everything in this world—",
    "opening.story.18": "objects, memories, abilities, all of it.",
    "opening.story.19": "One day, a Cube's power spoke to a king:",
    "opening.story.20": "—Gather the seven colors.—",
    "opening.story.21": "What happens when all seven are gathered?",
    "opening.story.22": "As each nation's ambition, scheme, and ideal collide,",
    "opening.story.23": "the battle over the seven colors",
    "opening.story.24": "begins now.",

    // --- Shop ---
    "shop.title": "Shop",
    "shop.cat.pieceSkin": "🎲 Piece skins",
    "shop.cat.cardBack": "🂠 Card backs",
    "shop.cat.playmat": "🟩 Playmats",
    "shop.cat.background": "🖼️ Backgrounds",
    "shop.cat.pet": "🐾 Pets",
    "shop.cat.avatar": "😀 Avatars",
    "shop.cat.mydeck": "🃏 Deck slots",
    "shop.ribbon.free": "Free",
    "shop.ribbon.owned": "Owned",
    "shop.balance.loginPrompt": "Log in to earn currency",
    "shop.balance": "Balance: 🪙 {n}",
    "shop.completion": "🏆 Collection: {percent}% ({owned}/{total})",
    "shop.petTip": "Click to make it move",
    "shop.alert.notEnough": "Not enough currency.",
    "shop.alert.alreadyOwned": "Already owned.",
    "shop.alert.loginNeeded": "Please log in.",
    "shop.alert.buyLoginNeeded": "You need to log in to buy.",
    "shop.buying": "Buying...",
    "shop.purchased": "Purchased “{name}”!",
    "shop.buyFailed": "Purchase failed ({msg})",

    // --- Rankings ---
    "rank.title": "📊 Rankings",
    "rank.cat.winRate": "Win rate",
    "rank.cat.wins": "Wins",
    "rank.cat.matches": "Matches",
    "rank.value.winRate": "{v}%",
    "rank.value.wins": "{v} W",
    "rank.value.matches": "{v} G",
    "rank.empty": "No eligible players yet.",
    "rank.rules.title": "Ranking rules",
    "rank.rules.b1": "・The Win-Rate Top 3 ranking only includes players whose match count exceeds 50% of the average match count among players who have actually played — so players with very few matches can't reach the top after just a few games.",
    "rank.rules.border": "Current average match count among active players: {average} → eligibility threshold: more than {border} matches",
    "rank.rules.b2": "・Tie-break order: ① win rate → ② wins → ③ matches; if all are equal, players share the same rank.",
    "rank.rulesBtnTip": "View ranking rules",
    "rank.loading": "Loading…",
    "rank.loadFail": "Failed to load rankings. Please check your connection.",
    "rank.iconTip": "Open rankings",
    "rank.iconCaption": "Rankings",
    "rank.iconDetail": "Check the win-rate, wins, and matches rankings.",

    "phase.titleSuffix": "{label} Phase",
  },
};

export function t(key, params) {
  const lang = getLang();
  let s = (UI[lang] && UI[lang][key]) ?? UI.ja[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}
