// アプリのUI文言（メニュー・ボタン等）の多言語化。カードのテキスト(card-text)とは別レイヤー。
// t(key, params) が現在の言語(getLang)の文字列を返す。未定義キーは ja にフォールバックし、
// ja にも無ければキー文字列をそのまま返す（開発中の抜けが画面に見えるように）。
// params は {name} 形式のプレースホルダを置換する（例: t("home.comingSoon", {label:"X"})）。
//
// UI英語化は段階的に進める。まずは最も目に付く画面（ホーム）から。翻訳済みのキーだけを
// ここに足していき、各ファイルはハードコード文字列を t("...") に置き換える。
import { getLang } from "./i18n.js";

const UI = {
  ja: {
    // --- ホーム画面（home-screen.js） ---
    "home.subtitle": "ホーム",
    "home.tile.tutorial": "物語チュートリアル",
    "home.tile.match": "CPUマッチ＆フレンドリーマッチ",
    "home.tile.ranked": "フリーマッチ（ランク戦）",
    "home.tile.shop": "ショップ",
    "home.tile.ranking": "ランキング",
    "home.tile.mypage": "マイページ／マイデッキ編集",
    "home.tile.codex": "図鑑／ルールブック",
    "home.tile.news": "お知らせ／更新情報",
    "home.comingSoon": "「{label}」は近日公開予定です。お楽しみに！",
    "home.comingSoonBadge": "近日公開",
    "home.newBadge": "NEW",
    "home.matchChoice.title": "対戦モードを選択",
    "home.matchChoice.friendly": "フレンドリーマッチ",
    "home.matchChoice.friendlyDesc": "オンラインで対戦（部屋を作る／参加する）",
    "home.matchChoice.cpu": "CPU戦（1人用）",
    "home.matchChoice.cpuDesc": "この端末でCPUと対戦（ログイン不要）",
    "home.matchChoice.difficultyLabel": "🤖 CPUの強さ（CPU戦のみ）",
    "home.matchChoice.difficultyHint": "新人＝ランダム／中級・上級＝賢い思考／最強＝伏せカードののぞき見あり",
    "home.matchChoice.countLabel": "👥 人数（CPU戦のみ）",
    "home.matchChoice.countHint": "あなた＋CPU（3人・4人はCPUが2体・3体に増えます）",
    "home.rankLabel": "あなたのランク",
    "home.rankAboutTitle": "ランク戦について",
    "home.waitingBadge": "🟢 {count}人が対戦募集中！",
    "common.back": "← 戻る",
    // --- CPUの強さ・人数（home / options 共有） ---
    "cpu.diff.rookie": "新人",
    "cpu.diff.intermediate": "中級",
    "cpu.diff.advanced": "上級",
    "cpu.diff.master": "最強",
    "cpu.count.2": "2人",
    "cpu.count.3": "3人",
    "cpu.count.4": "4人",
    // --- オプション（options-menu.js） ---
    "opt.title": "オプション",
    "opt.basicSettings": "基本設定",
    "opt.reset": "戻す",
    "opt.soundVolume": "効果音の音量",
    "opt.bgmVolume": "BGMの音量",
    "opt.langNote": "現在はカードのテキストのみ翻訳されます（メニュー等は順次英語化中）。",
    "opt.cardPreviewSize": "カード拡大プレビューのサイズ",
    "opt.cardPreviewSide": "カード拡大を出す向き",
    "opt.cpuSpeed": "CPUの速さ",
    "opt.cpuStrength": "CPUの強さ",
    "opt.resetAccount": "アカウント設定を初期化する",
    "opt.resetAccountDesc": "名前・アバター・駒スキン・プレイマット・カード裏面・背景画像を既定に戻します。",
    "opt.resetAccountConfirm": "本当に初期化しますか？（もう一度クリック）",
    "opt.resetAccountBusy": "初期化中…",
    "opt.resetAccountFailed": "初期化に失敗しました",
    "opt.statsLink": "🏆 戦績管理システムのプレイヤーと連携",
    "opt.statsLinkSelect": "選択する",
    "opt.statsLinkDone": "✅ 連携済みです",
    "opt.statsLinkGoogleOnly": "Googleアカウントでログインしていないと連携できません。",
    "opt.statsLinkReloginGoogle": "Googleアカウントでログインしなおす",
    "opt.pressKey": "キーを押してください…",
    "opt.sec.group.volume": "音量",
    "opt.sec.group.display": "表示・演出",
    "opt.sec.group.autoTimer": "自動処理・タイマー",
    "opt.chk.boardIllustOnly": "盤面のカードをイラストのみで表示（手札・拡大はそのまま）",
    "opt.chk.fixedHand": "自分の手札を画面下に固定する（盤面を拡大しても見切れない）",
    "opt.chk.flatten2d": "2D表示に切り替える（タブレットの点滅対策）",
    "opt.chk.fullscreen": "全画面表示にする（タブ/URL欄を隠す）",
    "opt.chk.opponentBaseTimer": "相手の基本時間のカウントダウンを表示する",
    "opt.chk.actionConfirm": "ロック・手札を使う前に確認する",
    "opt.sec.lockArea": "ロックエリア関連",
    "opt.chk.lockAreaBar": "ロックエリアバーを表示する",
    "opt.chk.lockColor": "ロックエリアの色を表示する",
    "opt.sec.modalDuration": "モーダル表示時間",
    "opt.sec.reduceAnim": "アニメーションを減らす（動作が重い時に）",
    "opt.chk.disableFlight": "移動アニメーション（駒・カードの飛翔）を無効にする",
    "opt.chk.disableArrival": "到達・ロック演出（光の柱・ロック画像等）を無効にする",
    "opt.chk.disableGlow": "常時光る演出（手番のグロー・砂時計ロープ等）を無効にする",
    "opt.chk.cpuAutoAdvance": "CPUの結果通知を自動で進める（OFFにするとクリックするまで表示）",
    "opt.rankedAutoFixed": "ランク戦では自動処理は常にONで固定されます。",
    "opt.autoProcessing": "カード効果を自動処理する",
    "opt.emergencyEndTurn": "🚨 緊急ターン終了",
    "opt.sec.cpuBattle": "CPU戦（1人用）",
    "opt.sec.rankedNotify": "ランク戦の通知",
    "opt.sec.shortcuts": "ショートカットキー（プレイヤー用ボタン）",
    "opt.shortcutRecommended": "⭐ おすすめ",
    "opt.adminMode": "⚙ 管理者モード",
    "opt.notify.enable": "対戦相手が現れたら通知する",
    "opt.notify.timeLabel": "通知してもいい時間帯",
    "opt.notify.hint": "開始と終了を同じ時刻にすると終日OKです。開始＞終了なら夜をまたぎます（例 22時〜6時）。",
  },
  en: {
    // --- Home screen ---
    "home.subtitle": "Home",
    "home.tile.tutorial": "Story Tutorial",
    "home.tile.match": "CPU & Friendly Match",
    "home.tile.ranked": "Free Match (Ranked)",
    "home.tile.shop": "Shop",
    "home.tile.ranking": "Rankings",
    "home.tile.mypage": "My Page / Deck Editor",
    "home.tile.codex": "Codex / Rulebook",
    "home.tile.news": "News / Updates",
    "home.comingSoon": "“{label}” is coming soon. Stay tuned!",
    "home.comingSoonBadge": "Coming soon",
    "home.newBadge": "NEW",
    "home.matchChoice.title": "Choose a match mode",
    "home.matchChoice.friendly": "Friendly Match",
    "home.matchChoice.friendlyDesc": "Play online (create or join a room)",
    "home.matchChoice.cpu": "CPU Match (solo)",
    "home.matchChoice.cpuDesc": "Play against the CPU on this device (no login)",
    "home.matchChoice.difficultyLabel": "🤖 CPU strength (CPU match only)",
    "home.matchChoice.difficultyHint": "Rookie = random / Intermediate & Advanced = smart AI / Master = peeks at face-down cards",
    "home.matchChoice.countLabel": "👥 Players (CPU match only)",
    "home.matchChoice.countHint": "You + CPU (3 / 4 players add 2 / 3 CPUs)",
    "home.rankLabel": "Your rank",
    "home.rankAboutTitle": "About ranked play",
    "home.waitingBadge": "🟢 {count} looking for a match!",
    "common.back": "← Back",
    // --- CPU strength / player count (shared home / options) ---
    "cpu.diff.rookie": "Rookie",
    "cpu.diff.intermediate": "Intermediate",
    "cpu.diff.advanced": "Advanced",
    "cpu.diff.master": "Master",
    "cpu.count.2": "2 players",
    "cpu.count.3": "3 players",
    "cpu.count.4": "4 players",
    // --- Options ---
    "opt.title": "Options",
    "opt.basicSettings": "Settings",
    "opt.reset": "Reset",
    "opt.soundVolume": "Sound effects volume",
    "opt.bgmVolume": "Music volume",
    "opt.langNote": "Currently only card text is translated (menus are being localized).",
    "opt.cardPreviewSize": "Card zoom preview size",
    "opt.cardPreviewSide": "Card zoom direction",
    "opt.cpuSpeed": "CPU speed",
    "opt.cpuStrength": "CPU strength",
    "opt.resetAccount": "Reset account settings",
    "opt.resetAccountDesc": "Restores name, avatar, piece skin, playmat, card back and background to defaults.",
    "opt.resetAccountConfirm": "Really reset? (click again)",
    "opt.resetAccountBusy": "Resetting…",
    "opt.resetAccountFailed": "Reset failed",
    "opt.statsLink": "🏆 Link a Battle Record player",
    "opt.statsLinkSelect": "Select",
    "opt.statsLinkDone": "✅ Linked",
    "opt.statsLinkGoogleOnly": "You must be signed in with Google to link.",
    "opt.statsLinkReloginGoogle": "Sign in again with Google",
    "opt.pressKey": "Press a key…",
    "opt.sec.group.volume": "Volume",
    "opt.sec.group.display": "Display & Effects",
    "opt.sec.group.autoTimer": "Auto-processing & Timer",
    "opt.chk.boardIllustOnly": "Show board cards as illustration only (hand & zoom unchanged)",
    "opt.chk.fixedHand": "Pin my hand to the bottom (stays visible when the board is zoomed)",
    "opt.chk.flatten2d": "Switch to 2D view (fixes tablet flicker)",
    "opt.chk.fullscreen": "Fullscreen (hide tabs / address bar)",
    "opt.chk.opponentBaseTimer": "Show the opponent's base-time countdown",
    "opt.chk.actionConfirm": "Confirm before locking / using a hand card",
    "opt.sec.lockArea": "Lock Area",
    "opt.chk.lockAreaBar": "Show the Lock Area bar",
    "opt.chk.lockColor": "Show Lock Area colors",
    "opt.sec.modalDuration": "Modal display time",
    "opt.sec.reduceAnim": "Reduce animations (if performance is poor)",
    "opt.chk.disableFlight": "Disable movement animation (piece / card flight)",
    "opt.chk.disableArrival": "Disable arrival / lock effects (light pillars, lock images, etc.)",
    "opt.chk.disableGlow": "Disable constant glow (turn glow, hourglass rope, etc.)",
    "opt.chk.cpuAutoAdvance": "Auto-advance CPU result notices (off = shows until clicked)",
    "opt.rankedAutoFixed": "Auto-processing is always ON in ranked matches.",
    "opt.autoProcessing": "Auto-process card effects",
    "opt.emergencyEndTurn": "🚨 Emergency end turn",
    "opt.sec.cpuBattle": "CPU Match (solo)",
    "opt.sec.rankedNotify": "Ranked match notifications",
    "opt.sec.shortcuts": "Shortcut keys (player buttons)",
    "opt.shortcutRecommended": "⭐ Recommended",
    "opt.adminMode": "⚙ Admin mode",
    "opt.notify.enable": "Notify me when an opponent appears",
    "opt.notify.timeLabel": "Allowed notification hours",
    "opt.notify.hint": "Same start and end = all day. Start > end wraps overnight (e.g. 22:00–6:00).",
  },
};

export function t(key, params) {
  const lang = getLang();
  let s = (UI[lang] && UI[lang][key]) ?? UI.ja[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}
